KQUB-436: Allow time for agents to update disposition and notes after a session
2600hz/kazoo-core pull request #1008
Opened 2024-11-22 16:45 UTC by Navoda626

adding node accessor functions for kz_doc

Main PR: https://github.com/2600hz/kazoo-qubicle/pull/1165

2024-12-04 18:51 UTC, danielfinke requested changes
Blocking for review later

2024-12-18 16:50 UTC, mark2600 approved these changes

2024-12-19 00:02 UTC, danielfinke approved these changes

2024-12-19 00:02 UTC, danielfinke commented on kazoo_documents/src/kz_doc.erl
> +-spec node(doc()) -> kz_term:ne_binary() | 'undefined'.
```suggestion
-spec node(doc()) -> kz_term:api_ne_binary().
```

2024-12-19 13:42 UTC, merged