KPIV-65: Enhance Dial Sip Support for Kazoo Integration
2600hz/kazoo-core pull request #1042
Opened 2024-12-20 08:30 UTC by dhuynh-Kazoo

Support custom-sip-headers, transport type, and authentication in INVITE sip message

2025-01-21 20:26 UTC, dhuynh-Kazoo commented
TwiML test flow 
```
<?php
header("content-type: text/xml");
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
?>

<Response>
    <Say> Going to test dial action! Thank you</Say>
    <Dial>
        <Sip username="admin" password="1234">
            sip:wbdemo@conf.zipdx.com;transport=udp
        </Sip>
    </Dial>
</Response>
```

2025-01-30 04:00 UTC, dhuynh-Kazoo commented
Hi @jamesaimonetti and @lazedo, could you please help me review that?

2025-02-26 20:31 UTC, icehess requested changes

2025-02-26 20:31 UTC, icehess commented on kazoo_translator/src/converters/kzt_twiml_dial.erl
> +       %% ,{<<"Outbound-Callee-ID-Name">>, 'undefined'}
Remove dead codes.

2025-02-26 21:36 UTC, icehess approved these changes

2025-02-26 21:37 UTC, merged

2025-03-03 06:29 UTC, dhuynh-Kazoo commented
5.4 backport:

[[5.4] KPIV-65: Enhance Dial Sip Support for Kazoo Integration](https://github.com/2600hz/kazoo-core/pull/1087)