Functions Added to map
2600hz/kazoo-core pull request #105
Opened 2020-10-26 20:06 UTC by kdamas93

internal_rate_cost  -> pvt_rate_cost
internal_surchage  ->  pvt_rate_surcharge

2020-10-27 17:04 UTC, jamesaimonetti requested changes

2020-10-27 17:04 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_rates.erl
> +        Value-> Doc = kz_json:set_value(<<"pvt_rate_cost">>, Value, Rate),
You could use `kz_json:set_values([{<<"pvt_rate_cost">>, Value}, {<<"internal_rate_cost">>, 'null'}], Rate)` I believe.

Also, mind your spacing and indentation. `Doc =` should be dropped to a newline. The project aims for keeping lines under 80 characters when feasible.

2020-10-27 17:04 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_rates.erl
> +        Value-> Doc = kz_json:set_value(<<"pvt_rate_surcharge">>, Value, Rate),
Similarly here.

2020-10-28 15:57 UTC, jamesaimonetti requested changes

2020-10-28 15:57 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_rates.erl
> +            kz_json:set_values([{<<"pvt_rate_cost">>, Value},
As a matter of project style, this should be formatted as:

```erlang
            kz_json:set_values([{<<"pvt_rate_cost">>, Value}
                               ,{<<"internal_rate_cost">>, 'null'}
                               ]
                              ,Rate
                              )
```

I would recommend taking a few minutes to peruse the [Contributing guide](https://github.com/2600hz/kazoo5/blob/master/CONTRIBUTING.md) to familiarize yourself with KAZOO's quirks :)
[](url)
More substantially, the module has `set_private_cost/2` and `set_private_surcharge/2` which use `pvt_internal_rate_cost` and `pvt_rate_surcharge` respectively.

It would seem that part of this ticket's work should be to make sure that the pvt keys are used consistently in kt_rates, hotornot, crossbar, and wherever else these values may be exposed.

2020-10-30 21:15 UTC, merged

2020-10-30 21:15 UTC, jamesaimonetti commented
@kdamas93 thanks for sticking it out with this one!

2020-10-30 21:17 UTC, kdamas93 commented
Thanks to you @jamesaimonetti !