CAG-31: Check for different id in options
2600hz/kazoo-core pull request #178
Opened 2020-12-18 00:09 UTC by jamesaimonetti

Check using from_user as well

delete accounts version if its lingering

2020-12-19 01:14 UTC, lazedo requested changes
lets talk

2020-12-22 08:07 UTC, lazedo commented on kazoo_documents/src/kzd_fetch.erl
> +
is this still needed ?

2020-12-22 08:24 UTC, lazedo commented on kazoo_directory/src/kz_directory_device.erl
> +        'true' -> maybe_from_options(EndpointId, AccountId, Without, kz_doc:id(Endpoint))
i think we should be using `Endpoint-ID` or `kzd_endpoint:id(Endpoint)`  instead of `kz_doc:id(Endpoint)`

2020-12-22 16:24 UTC, jamesaimonetti commented on kazoo_directory/src/kz_directory_device.erl
> +        'true' -> maybe_from_options(EndpointId, AccountId, Without, kz_doc:id(Endpoint))
Hmm, I'll check but when I was logging `Endpoint` i needed `_id` to get the new ID

2020-12-23 13:57 UTC, lazedo commented on kazoo_directory/src/kz_directory_device.erl
> +
this logic seems a duplication (and variant) of `kz_directory_endpoint` . i like the `props:take_value` so it doesn't repeat, maybe add that logic to `kz_directory_endpoint:maybe_from_options` and drop the changes here.
`kz_directory_endpoint:profile/4` will route to proper module and that's where we can add the `metadevice` handling

2020-12-23 13:57 UTC, lazedo commented on kazoo_directory/src/kz_directory_endpoint.erl
> +            profile(NewId, AccountId, Options, kz_doc:type(Endpoint))
see comment in `kz_directory_device`

2020-12-24 00:25 UTC, merged