KZOO-149: Add sftp support
2600hz/kazoo-core pull request #205
Opened 2021-01-21 19:59 UTC by holy-batman

This adds support for ssh servers to be uses a media saving locations, the ssh servers are automatically added to known_host file.

This module has been tested with a ssh server, using username and password for authentication to save and retrieve media.

Url example: `sftp://user:pass@host_url:port/foder_location`

2021-01-21 21:36 UTC, lazedo requested changes
add sftp in a new module, don't touch the ftp module.
make sure you test this with data plans, ensure that you can save & read an attachment

2021-01-22 23:11 UTC, holy-batman commented
@lazedo changes have been made as requested.

2021-01-22 23:19 UTC, holy-batman commented
requires https://github.com/2600hz/kazoo-media-mgr/pull/10

2021-01-25 18:54 UTC, jamesaimonetti requested changes

2021-01-25 18:54 UTC, jamesaimonetti commented on kazoo_attachments/src/kz_att_sftp.erl
> +        {'ok', Pid, _} -> handle_fetch(Pid, ssh_sftp:read_file(Pid, FullPath, Options));
`Options` should be a `Timeout` according to the spec:

```erlang
-spec read_file(ChannelPid, File, Timeout) -> {ok, Data} | Error when
      ChannelPid :: pid(),
      File :: string(),
      Data :: binary(),
      Timeout :: timeout(),
      Error :: {error, reason()}.
read_file(Pid, Name, FileOpTimeout) ->
```

2021-01-25 19:02 UTC, jamesaimonetti commented on kazoo_attachments/src/kz_att_sftp.erl
> +    {Host, Port, [{'timeout', 5000}, {'user', User}, {'password', Pass}, {'silently_accept_hosts', 'true'}]};
Should be

```erlang
{Host, Port
 ,[{'timeout', 5000}
   ,{'user', User}
   ,{'password', Pass}
   ,{'silently_accept_hosts', 'true'}
  ]
 }
```

2021-01-25 19:15 UTC, jamesaimonetti commented on kazoo_attachments/src/kz_att_sftp.erl
> +    {Host, 22, [{'timeout', 5000}, {'user', User}, {'password', Pass}, {'silently_accept_hosts', 'true'}]}.
Let's also look for timeout in the storage plan options and, if not present, default to 10s (please use `10 * ?MILLISECONDS_IN_SECOND` so we don't have magic numbers floating around).

2021-01-25 22:12 UTC, holy-batman commented on kazoo_attachments/src/kz_att_sftp.erl
> +    {Host, Port, [{'timeout', 5000}, {'user', User}, {'password', Pass}, {'silently_accept_hosts', 'true'}]};
done :)

2021-01-25 22:18 UTC, merged