KCRO-97: Add function for building metadata for given object
2600hz/kazoo-core pull request #251
Opened 2021-04-12 16:23 UTC by harenson

Dependency for:
- https://github.com/2600hz/kazoo-crossbar/pull/175
- https://github.com/2600hz/kazoo-properly/pull/53

2021-04-21 20:34 UTC, jamesaimonetti requested changes

2021-04-21 20:34 UTC, jamesaimonetti commented on kazoo_documents/src/kz_doc.erl
> +    metadata(id(Doc), created(Doc), modified(Doc), kz_json:get_json_value(<<"_read_only">>, Doc)).
_read_only will never exist on the doc, it is added to response payloads and stripped if included on requests.

2021-04-21 20:40 UTC, harenson commented on kazoo_documents/src/kz_doc.erl
> +    metadata(id(Doc), created(Doc), modified(Doc), kz_json:get_json_value(<<"_read_only">>, Doc)).
It is an special case which is explained within metadata/3, it only  happens with phone_numbers API responses:

```
%% phone_numbers API is the only one that doesn't use crossbar_doc module for loading
%% database documents, it loads those in its own way and the returned document has the
%% created and modified fields within a _read_only object.
```

2021-04-28 18:26 UTC, jamesaimonetti requested changes

2021-04-28 18:26 UTC, jamesaimonetti commented on kazoo_numbers/src/knm_phone_number.erl
> +    ExistingRO = kz_json:get_json_value(<<"_read_only">>, JObj, kz_json:new()),
This is not a phone numbers thing. `_read_only` is for the API response.

2021-04-28 18:28 UTC, harenson commented on kazoo_numbers/src/knm_phone_number.erl
> +    ExistingRO = kz_json:get_json_value(<<"_read_only">>, JObj, kz_json:new()),
ReadOnly was already being handled by this module on this function because numbers response is built on this module, not on the API module (cb_phone_numbers).

2021-04-28 19:58 UTC, jamesaimonetti commented on kazoo_numbers/src/knm_phone_number.erl
> +    ExistingRO = kz_json:get_json_value(<<"_read_only">>, JObj, kz_json:new()),
Doesn't cb_phone_numbers use crossbar_doc:handle_datamgr_success after fetching the number now? https://github.com/2600hz/kazoo-crossbar/pull/175/files#diff-ceed15a72fa876b80f5d29c69a601b81ded5c873e21ff697d0fff4fbf5ceca49R481

2021-04-28 20:03 UTC, harenson commented on kazoo_numbers/src/knm_phone_number.erl
> +    ExistingRO = kz_json:get_json_value(<<"_read_only">>, JObj, kz_json:new()),
Yes, but it doesn't have the phone_number document to retrieve the metadata information from. The only data crossbar_doc have access to is the data built by `knm_phone_number:to_public_json/1` function.

2021-04-29 21:50 UTC, merged