PROD-169: Split out failover number from forward number
2600hz/kazoo-core pull request #257
Opened 2021-04-23 21:57 UTC by icehess

Duplicate call forwarding settings into a failover object (account, user, device) and remove ‘failover’ as a call forward option.

The intend is to allow users to be able to change their call forwarding settings without impacting the failover settings and have failover set independently from forward.

2021-04-23 22:24 UTC, icehess commented
Circular Required PR:
https://github.com/2600hz/kazoo-crossbar/pull/179
https://github.com/2600hz/kazoo-ecallmgr/pull/88

Related PRs:
https://github.com/2600hz/kazoo-callflow/pull/70
https://github.com/2600hz/kazoo-callthru-us/pull/16
https://github.com/2600hz/kazoo-locations/pull/8

2021-04-23 22:35 UTC, icehess commented
It seems `kz_endpoint_v4` needs especial handling for failover:
https://github.com/2600hz/kazoo-core/blob/master/kazoo_endpoint/src/kz_endpoint_v4.erl#L1286

`maybe_build_failover/2` is calling `create_call_fwd_endpoint/3` which it reads all fwd values from `call_forward` object instead of `call_failover`.

2021-04-23 23:05 UTC, lazedo requested changes
minor potential crash, the rest looks good

2021-04-23 23:05 UTC, lazedo commented on kazoo_endpoint/src/kz_endpoint_v4.erl
> +    case kzd_call_failover:enabled(kzd_devices:call_failover(Endpoint)) of
`kzd_devices:call_failover(Endpoint)` may return `undefined`

2021-04-23 23:05 UTC, lazedo commented on kazoo_endpoint/src/kz_endpoint_v4.erl
> +    case kzd_call_forward:enabled(kzd_devices:call_forward(Endpoint)) of
`kzd_devices:call_forward(Endpoint)` may return `undefined`

2021-04-24 01:52 UTC, lazedo requested changes
just noticed this. please check the result of the merge

2021-04-24 01:52 UTC, lazedo commented on kazoo_endpoint/src/kz_endpoint_v5.erl
> +            kz_json:set_value(Key, Merged, Endpoint)
if the result of the `merge` is empty or `not enabled` then we should `not` set the key. please change this in `call_forward` too

2021-04-26 22:42 UTC, icehess commented on kazoo_endpoint/src/kz_endpoint_v5.erl
> +            kz_json:set_value(Key, Merged, Endpoint)
Done. 
FYI we always set the value without checking if the merge result is empty or not for all other attributes.

2021-04-26 22:43 UTC, icehess commented
@lazedo I also added a migration command to split failover from call_forward.

2021-04-27 00:41 UTC, lazedo commented
> It seems `kz_endpoint_v4` needs especial handling for failover:
> https://github.com/2600hz/kazoo-core/blob/master/kazoo_endpoint/src/kz_endpoint_v4.erl#L1286
> 
> `maybe_build_failover/2` is calling `create_call_fwd_endpoint/3` which it reads all fwd values from `call_forward` object instead of `call_failover`.

i would prefer to drop `all` changes from `v4` . `v4` is used to build the endpoint and is not handled in freeswitch as a `kazoo-endpoint`

2021-05-23 00:33 UTC, merged