KZOO-158: Add rename_and_refresh_app functionality
2600hz/kazoo-core pull request #270
Opened 2021-06-21 20:00 UTC by harenson

After renaming an application's folder, this functionality can be used to rename the application on all the accounts using it.

2021-06-22 00:46 UTC, icehess requested changes

2021-06-22 00:46 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Keys = [{[<<"quantities">>, Qty, Level, PrevName], [<<"quantities">>, Qty, Level, NewName]}
Do not change service doc at all.

First let change name appear normally on the next bill/or service notification.
Secondly change service plan docs. change the `applications` on the root of document. Then maybe run reconcile  services to update the service doc.

2021-06-22 00:46 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    {'ok', MetaData} = find_metadata(AppPath),
Handle erros gracefully. If operation on one account fails the whole operation should not fail. Just print this account failed because of this error

2021-06-22 00:46 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    {'ok', AppDoc} = kzd_apps_store:fetch(Account),
Handle errors gracefully. see above.

2021-06-22 00:46 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +                  ]
What about `whitelabel` document?

2021-06-22 00:54 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Keys = [{[<<"quantities">>, Qty, Level, PrevName], [<<"quantities">>, Qty, Level, NewName]}
Service doc doesn't have `applications`, _service plans_ doc has. For this to work I guess it is better to start from top level account, change all its service plans docs, run `kz_services:reconcile/1` and go a level down and repeat.

That is just a thought. I open to other suggestion :)

Basically if account is sub, you need to update service plans on its reseller or master or wherever that plans is defined. then you need to run reconcile.

There is a change to may skip reconcile, if we change the plan service doc will fix it self over time or on the next monthly run eventually.

2021-07-21 16:05 UTC, harenson commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    {'ok', MetaData} = find_metadata(AppPath),
At this point it is still doing changes on the master account, if there is any failure at this point, the execution should not continue, just fail.

2021-07-21 16:06 UTC, harenson commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +                  ]
There is nothing related to applications' metadata within that document, or at least I didn't see anything related.

2021-07-30 19:23 UTC, harenson commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Keys = [{[<<"quantities">>, Qty, Level, PrevName], [<<"quantities">>, Qty, Level, NewName]}
ServicePlan documents don't have application name anymore, it just makes use of the application-id to keep track of applications enabled for a given accounts. Also, just by renaming the application within the master account, rename the application within apps_store document for each account, and then run `kz_services:reconcile/1` is enough, not need to touch service_plan documents.

2021-08-10 23:06 UTC, merged