Generate tokens based on stream chat HS256
2600hz/kazoo-core pull request #311
Opened 2021-10-12 20:18 UTC by kdamas93

2021-10-12 21:24 UTC, jamesaimonetti requested changes

2021-10-12 21:24 UTC, jamesaimonetti commented on kazoo_auth/src/kz_auth_jwt.erl
> +    case Digest of
I'd like to see pattern matching used the function header to do the signing vs a case statement:

```erlang
sign(#{digest := 'hs256'
      ,key := Key
      ,jwt := #{payload := Payload} = JWT
      } = Map) ->
    Signature = ...
    Map#{...};
sign(#{digest := Digest
      ,key := Key
      ,jwt := #{payload := Payload} = JWT
      } = Map) ->
    Signature = ...
    Map#{...}.
```

Alternatively, since the second expression in each clause is the same, call a helper function to build the signature:

```erlang
    Signature = build_signature(Digest, Payload, Key),
    Map#{...}.

build_signature('hs256', Payload, Key) ->
    encode(mac(hmac, sha256, Key, Payload));
build_signature(Digest, Payload, Key) ->
    encode(sign(Payload, Digest, Key)).
```

Go ahead and drop the map's items on their own lines too.

2021-10-12 21:24 UTC, jamesaimonetti commented on kazoo_auth/src/kz_auth_jwt.erl
> +
Seems excessive :)

2021-10-13 22:11 UTC, kdamas93 commented on kazoo_auth/src/kz_auth_jwt.erl
> +    case Digest of
Changes made

2021-10-13 22:11 UTC, kdamas93 commented on kazoo_auth/src/kz_auth_jwt.erl
> +
Ty

2021-10-13 22:16 UTC, lazedo commented on kazoo_auth/src/kz_auth_jwt.erl
> +  Map#{jwt => JWT#{signature => Signature,token => <<Payload/binary, ".", Signature/binary>>}};
this is not needed with the changes below

2021-10-13 22:40 UTC, lazedo requested changes

2021-10-13 22:40 UTC, lazedo commented on kazoo_auth/src/kz_auth_jwt.erl
> +    Map#{jwt => JWT#{signature => Signature,token => <<Payload/binary, ".", Signature/binary>>}};
remove this

2021-10-14 10:30 UTC, lazedo approved these changes

2021-10-22 21:57 UTC, merged