Adding changes to send a conference email invite from branding app
2600hz/kazoo-core pull request #442
Opened 2022-06-08 00:53 UTC by kdamas93

2022-06-22 17:26 UTC, icehess requested changes

2022-06-22 17:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_notifications.erl
> +                                                            ,<<"To">>]}
```suggestion
              ,{fun kapi_definition:set_optional_headers/2, [<<"Conference-Link">>
                                                            | ?DEFAULT_OPTIONAL_HEADERS
                                                            ]}
```

2022-06-25 00:30 UTC, kdamas93 commented on kazoo_amqp/src/api/kapi_notifications.erl
> +                                                            ,<<"To">>]}
The changes have already been made

2022-06-30 16:41 UTC, icehess approved these changes

2022-06-30 17:19 UTC, merged