[Master] KZOO-264 : Add TCP and UDP toggle for DNS Query
2600hz/kazoo-core pull request #455
Opened 2022-06-29 13:09 UTC by sanjeevie6353

Added changes to allow TCP query for DNS lookup. Default is TCP query.

Linked changes available on both kazoo-crossbar & kazoo-ecallmgr under branch name KZOO-264

https://github.com/2600hz/kazoo-crossbar/pull/308
https://github.com/2600hz/kazoo-ecallmgr/pull/171

2022-06-29 14:01 UTC, lazedo requested changes
you're adding dependency for kapps_config in this library, is there a reason for this ? applications using network utils will have kapps_config dependency which is not intended on some application that don't use kazoo_apps/kazoo_appex. you can query/setup the option on appex and pass it to network utils

2022-06-29 14:35 UTC, lazedo commented on kazoo_appex/src/appex_bluepak.erl
> +                end,
move this to a fun

2022-06-29 14:35 UTC, lazedo commented on kazoo_appex/src/appex_bluepak.erl
> +                  , Options
invoke the fun here

2022-06-29 14:35 UTC, lazedo commented on kazoo_stdlib/src/kz_network_utils.erl
> +
remove this change (spaces added)

2022-06-29 14:36 UTC, lazedo commented on kazoo_stdlib/src/kz_network_utils.erl
> -    end.
remove this change too

2022-07-07 16:48 UTC, sanjeevie6353 commented on kazoo_appex/src/appex_bluepak.erl
> +                end,
Moved to a function.
![image](https://user-images.githubusercontent.com/27858140/177827522-2e997331-a80e-4a88-a759-0b181b948f39.png)

2022-07-07 16:49 UTC, sanjeevie6353 commented on kazoo_appex/src/appex_bluepak.erl
> +                  , Options
Invoked it using the above function

2022-07-07 16:49 UTC, sanjeevie6353 commented on kazoo_stdlib/src/kz_network_utils.erl
> +
removed the change

2022-07-07 16:49 UTC, sanjeevie6353 commented on kazoo_stdlib/src/kz_network_utils.erl
> -    end.
removed this change.

2022-07-14 16:51 UTC, icehess commented
@sanjeevie6353 Isn't it better to move all these `use_tcp` configs from individual places to `kz_network_utils` as a global settings?

I think having separate config for this is excessive and cumbersome, generally if you need this option it needed by most of other places in Kazoo too, by having a global settings it is easier as admin of system to set it instead of forgetting to set this option in appex (which virtually all people will forget) but having setting in cb_whitelable.

2022-07-14 16:54 UTC, icehess commented
Or let ecallmgr, appex_client, cb_whitelabel fetch their ow `use_tcp` option, but remove their default value
and in `kz_network_util` if `usevc` is `undefined` then it fetches the global settings of `use_tcp`.

2022-07-14 17:19 UTC, jamesaimonetti commented
@icehess kz_network_utils, being in kazoo_stdlib, should not use kapps_config. Each app that uses these should override the default 'true' if they choose.

2022-07-14 17:32 UTC, icehess commented
@jamesaimonetti fair enough.

2022-07-15 20:56 UTC, merged