[Master] KTAS-2 : Update 'modb' task to allow optional archiving
2600hz/kazoo-core pull request #468
Opened 2022-07-28 19:45 UTC by sanjeevie6353

Added config option to allow deleting the 'modb' without archiving. default is false.

Changes on kazoo-core, kazoo-tasks and kazoo-crossbar.

2022-07-28 20:54 UTC, jamesaimonetti requested changes

2022-07-28 20:54 UTC, jamesaimonetti commented on kazoo_modb/src/kazoo_modb.erl
> +            case ArchiveBeforeDel of
I think you can just use boolean logic in one case statement:

```erlang
case should_archive(AccountMODb, Year, Month)
   andalso ArchiveBeforeDel
of
    'true' -> kz_datamgr:db_archive();
    'false' -> lager:info("not archiving first")
end
```

2022-07-28 20:55 UTC, jamesaimonetti commented on kazoo_modb/src/kazoo_modb.erl
> +            case ArchiveBeforeDel of
| should_archive/3 | ArchiveBeforeDel | kz_datamgr:db_archive/0 |
|------------------------|-------------------------|-----------------------------------|
| true | true | true |
| true | false | false |
| false | true | false |
|false | false | false |

2022-07-29 13:13 UTC, sanjeevie6353 commented on kazoo_modb/src/kazoo_modb.erl
> +            case ArchiveBeforeDel of
> I think you can just use boolean logic in one case statement:
> 
> ```erlang
> case should_archive(AccountMODb, Year, Month)
>    andalso ArchiveBeforeDel
> of
>     'true' -> kz_datamgr:db_archive();
>     'false' -> lager:info("not archiving first")
> end
> ```

I have a small concern on this.

- If the existing function should_archive/3 resolves to false, there will be no modb deletion
- If should_archive/3 resolves to true, the function needs to execute the db_delete (irrespective of the value of <<"archive_modb_before_delete">>) parameter.

So we might have to keep the current implementation.

2022-08-01 17:09 UTC, merged