KCRO-150: Enhance DELETE /users/{USER_ID} API
2600hz/kazoo-core pull request #498
Opened 2022-09-15 01:41 UTC by harenson

Dependency for https://github.com/2600hz/kazoo-crossbar/pull/344
Tests https://github.com/2600hz/kazoo-properly/pull/93

With this change, when deleting a user, either "all" or a list of crossbar's `object_types` may be included in the request (either in the request's body or query_string) for the API to take of deleting those along the user. There is also the possibility to include
"phone_numbers" in the objects list, which will instruct the users API to also release all the numbers associated to every callflow owned by the user.

2022-09-22 22:29 UTC, jamesaimonetti commented on kazoo_stdlib/src/props.erl
> +split(Fun, Props) ->
This is an interesting decision. Compare 10 runs on a list of 10,000 elements:
```
split() ->
    props:split(fun is_true/1, ?L).

split_p() ->
    lists:splitwith(fun is_true/1, ?L).

props_tests:split in 1.545273s
props_tests:split_p in 0.000000s
```

2022-09-22 23:12 UTC, jamesaimonetti commented on kazoo_stdlib/src/props.erl
> +split(Fun, Props) ->
Correction, use `lists:partition/2` but same timings apply:
```
props_tests:split in 1.545738s
props_tests:split_p in 0.002573s
```

2022-09-22 23:12 UTC, jamesaimonetti commented on kazoo_stdlib/src/props.erl
> +split(Fun, Props) ->
2nd point, tests for this functionality should be included in props_tests. I added a commit with a couple

2022-09-23 00:38 UTC, icehess requested changes

2022-09-23 00:38 UTC, icehess commented on kazoo_couch/priv/couchdb/views/account-crossbar_listings.json
> +        "by_ownerid": {
Why creating a new view? What functionality `by_ownerid_type` is not providing which makes you create new view?

If you just need to search for all docs owned by owner_id simply use `[{startkey, [OwnerId]}, {endkey, [OwnerId, kz_term:high_unicode_value()]}]`.

2022-09-23 17:29 UTC, harenson commented on kazoo_stdlib/src/props.erl
> +split(Fun, Props) ->
Ok, thank you for the heads up.

2022-09-23 17:29 UTC, harenson commented on kazoo_couch/priv/couchdb/views/account-crossbar_listings.json
> +        "by_ownerid": {
Good to know, thanks @icehess, I just changed it.

2022-09-23 21:56 UTC, merged