KZOO-271: Add optional mechanism to limit concurrent calls per endpoint
2600hz/kazoo-core pull request #512
Opened 2022-10-21 05:05 UTC by harenson

Depends on: https://github.com/2600hz/kazoo-crossbar/pull/362

This new mechanism allows to set a maximum concurrent calls limit per endpoint (device/user) or account-wide. When configure at device, user and account level, device's configuration takes precedence over user's configuration, and  user's configuration takes precedence over account's configuration.

2022-10-24 15:19 UTC, lazedo requested changes

2022-10-24 15:19 UTC, lazedo commented on kazoo_transactions/src/kz_endpoint_transactions.erl
> +
core libraries shuold not refer to applications

2022-10-27 18:25 UTC, harenson commented on kazoo_transactions/src/kz_endpoint_transactions.erl
> +
The endpoint_limit API was moved out of jonny5 and put into core/kazoo_call application instead.

2022-11-22 22:16 UTC, danielfinke requested changes
Looks good to me. Just have some minor asks/questions

2022-11-22 22:16 UTC, danielfinke commented on kazoo_amqp/src/api/kapi_call.erl
> +                ,{<<"Owner-ID">>, fun erlang:is_binary/1}
should the type for `<<"Realm">>` also be added?

2022-11-22 22:16 UTC, danielfinke commented on kazoo_amqp/src/api/kapi_call.erl
> +%% Takes {@link kz_term:proplist()}, creates JSON string or error.
can maybe omit this line since it's accounted for in the spec
```suggestion
```
same suggestion on L838

2022-11-22 22:16 UTC, danielfinke commented on kazoo_amqp/src/api/kapi_call.erl
> +
it looks like this fun could be removed if you switch the usage in `kapi_dialplan` to use `call_routing_key/3` instead

2022-11-22 22:16 UTC, danielfinke commented on kazoo_call/doc/endpoint_limit.md
> +%% If a call is placed from/to EndpointId, check should return true when quering for endpoint's limit
typo
```suggestion
%% If a call is placed from/to EndpointId, check should return true when querying for endpoint's limit
```

2022-11-22 22:16 UTC, danielfinke commented on kazoo_call/src/kapps_call.hrl
> +-ifndef(KAPPS_CALL_HEADERS).
convention
```suggestion
-ifndef(KAPPS_CALL_HRL).
```

2022-11-22 22:16 UTC, danielfinke commented on kazoo_stdlib/src/kz_maps.erl
> +-export([remove/2]).
should these `kz_maps` changes be split out into a separate PR? They don't seem related

2022-11-22 22:16 UTC, danielfinke commented on kazoo_stdlib/src/kz_maps.erl
> +remove([Key | Rem], Map) ->
this is very similar to `maps:without/2`

2022-11-22 22:16 UTC, danielfinke commented on kazoo_call/src/kapps_endpoint_limit.erl
> +%%% @doc RA (Raft) integration
is this still going to be a part of some Raft setup?

2022-11-22 22:48 UTC, lazedo requested changes
marking this as not mergeable

2022-11-22 23:06 UTC, lazedo commented on kazoo_amqp/src/api/kapi_call.erl
> +        ]).
this should go into a new kapi, lets leave this one for queries

2022-11-22 23:11 UTC, lazedo commented on kazoo_amqp/src/api/kapi_call.erl
> +                ,{<<"Owner-ID">>, fun erlang:is_binary/1}
don't add this here. you can add a `query_owner_channels` and hangdle it on ecall_fs_channels
also, as a requirement, add a `query_endpoint_channels`  and handle it on ecallmgr_channels with selector as ( authorizing_id = $1 or owner_id = $1 ) and an optional direction with `both` as default and adapt the selector for that

2022-11-22 23:22 UTC, lazedo commented on kazoo_stdlib/src/kz_maps.erl
> +    remove(Rem, maps:remove(Key, Map));
this looks wrong, what's the intent ?
#{a => #{a1 => #{a2 => #{a3 => #{xxx}}}}}
remove([a,a2,a3,xxx]) will remove remove `a` and should only remove `xxxx`

2022-11-22 23:23 UTC, lazedo commented on kazoo_stdlib/src/kz_maps.erl
> +    remove(Rem, maps:remove(Key, Map));
if the intent was to remove a list of keys, then as @danielfinke mentioned, `maps:without/2` is to be used and it shouldn't be here

2022-11-22 23:31 UTC, lazedo requested changes
lets split the pr.

lets merge the changes for the accessors, kapi_call (query_channels_by_owner_id, query_channels_by_endpoint), kazoo_endpoint, kazoo_directory

then lets do the corresponding changes on ecallmgr fs channels

then lets add the core kazoo_call and kapi limits changes 

then lets talk about where to put the listener that will call the channels_limits

also, lets try not to merge unrelated changes

2022-11-23 19:03 UTC, harenson commented on kazoo_amqp/src/api/kapi_call.erl
> +                ,{<<"Owner-ID">>, fun erlang:is_binary/1}
@lazedo Do you still want me to take care of these changes you requested here?

2022-11-23 19:06 UTC, harenson commented on kazoo_amqp/src/api/kapi_call.erl
> +
They are separated kapi modules. This routing key creation is per kapi module.

2022-11-23 19:10 UTC, harenson commented on kazoo_amqp/src/api/kapi_call.erl
> +        ]).
@lazedo Do you still want me to move this functions are out of this module and create a new one for it?

2022-11-23 19:13 UTC, harenson commented on kazoo_call/src/kapps_endpoint_limit.erl
> +%%% @doc RA (Raft) integration
No, it is not, removing it.

2022-11-23 19:14 UTC, harenson commented on kazoo_stdlib/src/kz_maps.erl
> +    remove(Rem, maps:remove(Key, Map));
This was a left-over from previous implementation. Removed.

2022-11-23 19:20 UTC, harenson commented on kazoo_amqp/src/api/kapi_call.erl
> +%% Takes {@link kz_term:proplist()}, creates JSON string or error.
Done.

2022-11-23 19:20 UTC, harenson commented on kazoo_call/doc/endpoint_limit.md
> +%% If a call is placed from/to EndpointId, check should return true when quering for endpoint's limit
Fixed.

2022-11-23 19:20 UTC, harenson commented on kazoo_stdlib/src/kz_maps.erl
> +-export([remove/2]).
Removed.

2022-11-23 19:21 UTC, harenson commented on kazoo_call/src/kapps_call.hrl
> +-ifndef(KAPPS_CALL_HEADERS).
Changed.

2022-11-23 19:31 UTC, lazedo commented
@harenson move this to draft

2022-11-23 19:32 UTC, lazedo commented on kazoo_amqp/src/api/kapi_call.erl
> +                ,{<<"Owner-ID">>, fun erlang:is_binary/1}
@harenson no, they're already done

2022-11-23 19:40 UTC, harenson commented
@lazedo Done, what changes do you want me to do before marking it as ready for review again?

2022-11-23 21:20 UTC, danielfinke commented on kazoo_call/src/kapps_endpoint_limit.erl
> +%%% This Source Code Form is subject to the terms of the Mozilla Public
missing `@doc`
```suggestion
%%% @doc This Source Code Form is subject to the terms of the Mozilla Public
```

2022-11-23 21:20 UTC, danielfinke commented on kazoo_call/src/kapps_call.hrl
> +-define(KAPPS_CALL_HEADERS, 'true').
need to update this line too
```suggestion
-define(KAPPS_CALL_HRL, 'true').
```

2022-11-24 05:04 UTC, harenson commented on kazoo_call/src/kapps_endpoint_limit.erl
> +%%% This Source Code Form is subject to the terms of the Mozilla Public
That is not documentation, but license information. I added a very short documentation to this module, anyway.

2022-11-24 05:04 UTC, harenson commented on kazoo_call/src/kapps_call.hrl
> +-define(KAPPS_CALL_HEADERS, 'true').
Nice catch, thank you.

2023-03-29 21:05 UTC, closed without merging