kcro-148-CommlandSelectorApi-master
2600hz/kazoo-core pull request #524
Opened 2022-11-09 17:23 UTC by kdamas93

Related changes for command selector API support, more detail can be found in this reference
https://github.com/2600hz/kazoo-crossbar/pull/374

2022-11-15 17:57 UTC, jamesaimonetti requested changes

2022-11-15 17:57 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_application_blocklist.erl
> +-author("kevin").
uneeded

2022-11-15 17:57 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_application_blocklist.erl
> +%%% @author kevin
Please find a module header comment block and re-use here

2022-11-15 17:57 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_application_blocklist.erl
> +    Routines = [fun(JObj) -> kz_doc:set_id(JObj, ?ID) end
See about using kz_json:exec_first/2 instead, then you can write it like:

```erlang
    Routines = [{fun kz_doc:set_id/2, ?ID}
               ,{fun kz_doc:set_account_id/2, kzs_util:format_account_id(Account)}
               ,{fun kz_doc:set_account_db/2, kzs_util:format_account_db(Account)}
               ,fun(JObj) ->
                        kz_json:set_value(ApplicationType, [], JObj)
                end
               ],
    kz_json:exec_first(Routines, kz_json:new()).
```

As a general rule, we try to use named functions as arguments instead of contructing anonymous funs (when possible). There's a performance penalty to building the fun then executing it vs passing a named fun and executing it.

2022-11-15 17:57 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_application_entitlement.erl
> +    Routines = [fun(JObj) -> kz_doc:set_id(JObj, ?ID) end
Same idea here

2022-11-17 19:13 UTC, kdamas93 commented on kazoo_documents/src/kzd_application_blocklist.erl
> +%%% @author kevin
Done.

2022-11-17 19:14 UTC, kdamas93 commented on kazoo_documents/src/kzd_application_blocklist.erl
> +    Routines = [fun(JObj) -> kz_doc:set_id(JObj, ?ID) end
Done ! Thanks!

2022-11-17 19:14 UTC, kdamas93 commented on kazoo_documents/src/kzd_application_entitlement.erl
> +    Routines = [fun(JObj) -> kz_doc:set_id(JObj, ?ID) end
Done ! Thanks!

2022-11-17 19:25 UTC, icehess requested changes

2022-11-17 19:25 UTC, icehess commented on kazoo_documents/src/kzd_application_blocklist.erl
> +                        kz_json:set_value(ApplicationType, [], JObj)
add an accessor and setter function for `application_type` here, and use it here instead of anonymous function.

2022-11-17 21:01 UTC, kdamas93 commented on kazoo_documents/src/kzd_application_blocklist.erl
> +                        kz_json:set_value(ApplicationType, [], JObj)
@icehess change made, thanks!

2022-11-18 18:26 UTC, icehess requested changes
I still don't understand why we need another function to init app.
We already have a proven working set of functions, like `init_apps`, `init_app`, `refresh_app`, `refresh_apps` and their rename functions. 

this only adds init_app.

What concerns me here that implementing this feature this way, it is not clear in what circumstances we should use init_app or init_applications, and this is highly confusing both to other developers and most importantly to ops and system_admins. Also give that there is no documentation, no spec and no comments.

What I would suggest to incorporate `application_type` to `metadata.json` of apps,
Commland apps, naturally add this field as they add the metadata.json. MUI apps will add or updates in the future.

By default for now, if application_type is missing we assume this monster-ui-app to make current non-updated mui metadata compatible and put less pressure in developers and system_admin about migration.

This there is absolutely no need to add these new functions, you just update functions like `find_metadata_application` and `maybe_update_app` to incorporate the application_type logic.

Also this way we don't need so much different copy of the same thing, like view or other functions/modules/schemas.

Basically what I'm asking is just add application_type to the existing `app` schema and update the logic to check and honor application_type in different places like here.

Feel free to reach out to me if you have questions.

2022-11-18 18:26 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +init_application(AppPath, AppUrl) ->
What is `AppUrl`?

2022-11-18 18:26 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    kz_json:set_value(<<"api_url">>, AppUrl, MetaData).
This is really crossbar Api url, what is this `AppUrl`?

2022-11-18 18:26 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    case kz_json_schema:validate(<<"application">>, kz_doc:public_fields(JSON)) of
I can find the `application` schema, is this new? How it is different from old `app`?

Also there is collision between application schema and application schema from kazoo-cpaas (which is totally different thing)

2022-11-18 18:26 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +        {'ok', _} -> {'ok', JSON};
```suggestion
        {'ok', _} -> {'ok', kzd_app:set_app_hash(JSON, kz_binary:rand_hex(16))};
```

2022-11-18 18:31 UTC, icehess requested changes

2022-11-18 18:31 UTC, icehess commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Doc = kz_json:delete_key(<<"source_url">>, Doc0),
Why deleting this? Removing this will break kazoo_appex.

2022-11-18 18:56 UTC, kdamas93 commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Doc = kz_json:delete_key(<<"source_url">>, Doc0),
@icehess I will squash all the commits to work based on a single commit and after that I will work/respond on your observations, thanks for the explanation

2022-11-18 21:03 UTC, icehess requested changes

2022-11-18 21:03 UTC, icehess commented on kazoo_documents/src/kzd_application_blocklist.erl
> +               ,{fun set_application_type/2, ApplicationType}
hmm, also do we want to set `doc_type` here?

2022-11-18 21:03 UTC, icehess commented on kazoo_documents/src/kzd_application_entitlement.erl
> +               ,{fun kz_doc:set_account_db/2, kzs_util:format_account_db(Account)}
hmm, also do we want to set `doc_type` here?

2022-11-29 21:12 UTC, kdamas93 commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +init_application(AppPath, AppUrl) ->
should be `ApplicationUrl`

2022-11-29 21:14 UTC, kdamas93 commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    case kz_json_schema:validate(<<"application">>, kz_doc:public_fields(JSON)) of
I just uploaded it, it's based on the app schema, it's basically a copy to isolate the new functionality from the existing one

2022-11-29 21:19 UTC, kdamas93 commented on kazoo_documents/src/kazoo_documents_maintenance.erl
> +    Doc = kz_json:delete_key(<<"source_url">>, Doc0),
I have not deleted it, when it does not appear it was because it was located in the wrong place, I had created it in crossbar but it is already in core

2022-11-29 21:20 UTC, kdamas93 commented on kazoo_documents/src/kzd_application_entitlement.erl
> +               ,{fun kz_doc:set_account_db/2, kzs_util:format_account_db(Account)}
I don't quite understand, how should the change be or is it unnecessary to use a macro?

2022-11-29 21:21 UTC, kdamas93 commented
> I still don't understand why we need another function to init app. We already have a proven working set of functions, like `init_apps`, `init_app`, `refresh_app`, `refresh_apps` and their rename functions.
> 
> this only adds init_app.
> 
> What concerns me here that implementing this feature this way, it is not clear in what circumstances we should use init_app or init_applications, and this is highly confusing both to other developers and most importantly to ops and system_admins. Also give that there is no documentation, no spec and no comments.
> 
> What I would suggest to incorporate `application_type` to `metadata.json` of apps, Commland apps, naturally add this field as they add the metadata.json. MUI apps will add or updates in the future.
> 
> By default for now, if application_type is missing we assume this monster-ui-app to make current non-updated mui metadata compatible and put less pressure in developers and system_admin about migration.
> 
> This there is absolutely no need to add these new functions, you just update functions like `find_metadata_application` and `maybe_update_app` to incorporate the application_type logic.
> 
> Also this way we don't need so much different copy of the same thing, like view or other functions/modules/schemas.
> 
> Basically what I'm asking is just add application_type to the existing `app` schema and update the logic to check and honor application_type in different places like here.
> 
> Feel free to reach out to me if you have questions.

This design was discussed in its initial version with Karl.

The purpose is to create a new `application` schema based on the current app schema.

I just added` init-application` to complete the application creation flow through the new `application` schema.
I understand that this is the idea to be able to differentiate or that there would not be problems of conflicts about the already existing functionality.
I understand that I would need to add the functions `init_applications`, `refresh_aplication`, `refresh_applications`

I can add the necessary/missing documentation but I would like to confirm if we will keep this architecture or choose to always handle it in the application schema with a new section in the metadata.

How would we reach an agreement or is the version proposed by you the one that we should follow?

I appreciate your time and level of detail, I am waiting for your comments and in parallel I will send you this answer in slack

2023-01-10 18:10 UTC, icehess requested changes

2023-01-10 18:10 UTC, icehess commented on kazoo_documents/src/kzd_application_blocklist.erl
> +               ,{fun set_application_type/2, ApplicationType}
Also please write JSON schema for this.

2023-01-10 18:10 UTC, icehess commented on kazoo_documents/src/kzd_application_entitlement.erl
> +               ,{fun kz_doc:set_account_db/2, kzs_util:format_account_db(Account)}
ALso please write JSON schema.

2023-06-15 20:52 UTC, jamesaimonetti requested changes
See crossbar review as well

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +    case rename_app('legacy', AppId, PrevName, NewName, [MA | Accounts]) of
Either this first arg `legacy` is wrong or the type in `rename_app/5` is wrong (tuple or ne_binary)

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +    case rename_app('legacy', AppId, PrevName, NewName, [MA | Accounts]) of
A question here too: in `rename_app/5` `AppType` is never used for anything, so why pass it around?

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +    case kzd_application:find_by_name(MasterAccountDb, AppName, AppType) of
You may want to put `<<AppType/binary>>` in the function clause to let dialyzer know, otherwise it complains that this function call won't work.

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +                {'ok', _} -> app('legacy',AppId);
I don't think the atom here is valid, right? `app/2` expects the tuple or ne_binary()

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +fix_apps_store_SUPP_212(_AppType, AppId) ->
Does this function call itself infinitely? The function is arity-2 and calls the same named function, arity 2, with diff args.

What tests do you have calling this function to show it works?

2023-06-15 20:52 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_application.erl
> +            {'ok', App};
why return the ok tuple when the spec says boolean() and the calling code above pattern matches for boolean?

I ask again, what tests use this code?

2023-06-19 23:05 UTC, kdamas93 commented on kazoo_documents/src/kazoo_ui_apps_maintenance.erl
> +fix_apps_store_SUPP_212(_AppType, AppId) ->
It is a function that has been inherited from **kazoo_documents_maintenance**, it was taken since the development of this module is based on the **kazoo_documents_maintenance**

2023-06-27 23:30 UTC, icehess commented
Required PRs:

- https://github.com/2600hz/kazoo-crossbar/pull/374
- https://github.com/2600hz/kazoo-core/pull/524
- https://github.com/2600hz/kazoo-properly/pull/156
- https://github.com/2600hz/kazoo-ast/pull/42

2023-07-12 15:44 UTC, merged