KZOO-324 : Adding possibility to configure default custom application variables to appear on CDRs
2600hz/kazoo-core pull request #541
Opened 2022-11-28 16:39 UTC by sanjeevie6353

KZOO-324 : Adding possibility to configure default custom application variables to appear on CDRs

Previously, the CDRs were printed with **custom application variables** only when the user has assigned them. 

This new feature will allow to define a set of  **custom application variables** in a system config. These defined sys.config values will always be available in the CDRs.

2022-11-30 18:48 UTC, jamesaimonetti commented on kazoo_call/src/kapps_call.erl
> +build_default_cavs([[ParentKey,ChildKey]| REST], UserDoc, CAVs) ->
I'm not sure about this construction.
What are ParentKey and ChildKey supposed to look like?

2022-11-30 18:49 UTC, jamesaimonetti commented on kazoo_call/src/kapps_call.erl
> +build_default_cavs([[ParentKey,ChildKey]| REST], UserDoc, CAVs) ->
If you have a user doc with `{"foo":{ "bar": {"baz":123}}}` and you want "foo.bar.baz" set as a CAV, what would Parent/Child be here?

2022-11-30 18:52 UTC, jamesaimonetti commented on kazoo_call/src/kapps_call.erl
> +build_default_cavs([[ParentKey,ChildKey]| REST], UserDoc, CAVs) ->
My thinking is, just use a list of paths (a path = ["foo", "bar", "baz"] so [ ["foo", "bar", "baz"], ["a", "b"], ["enabled"] ] would be the list), and if `kz_json:get_value(Path, UserJObj)` is undefined, move on; if a a value is found, `kz_json:set_value(Path, Value, CAVs)` it.

2022-11-30 18:54 UTC, jamesaimonetti commented on kazoo_endpoint/src/kz_endpoints_v5.erl
> +maybe_add_cavs_to_call(OwnerId, Data, Call) ->
I think this work should be done in kazoo_directory (like kz_directory_user, kz_directory_device, etc).
These CAVs should be present in the directory XML sent to FS for the endpoint.

2022-12-05 20:08 UTC, sanjeevie6353 commented on kazoo_call/src/kapps_call.erl
> +build_default_cavs([[ParentKey,ChildKey]| REST], UserDoc, CAVs) ->
This logic has been changed to implement `kz_json:get_value(Path, UserJObj)` and ` kz_json:set_value(Path, Value, CAVs)` logic

2022-12-05 20:09 UTC, sanjeevie6353 commented on kazoo_endpoint/src/kz_endpoints_v5.erl
> +maybe_add_cavs_to_call(OwnerId, Data, Call) ->
The logic has been moved to `kz_directory_device`

2022-12-06 10:04 UTC, lazedo requested changes

2022-12-06 10:04 UTC, lazedo commented on kazoo_directory/src/kz_directory_device.erl
> +
this shouldn't be done here
1.  `directory` should use `endpoint` data for device/user
2. these cavs should be set on kz_endpoint_v5 merge
3. default cavs should be configured for account/user/device
4. `Custom-Application-Vars` should be a `get_ne_json` on the endpoint (no defaults)

2022-12-06 10:36 UTC, lazedo commented on kazoo_directory/src/kz_directory_device.erl
> +
also, when building the default cavs on kz_endpoint merge, don't use last part of path for the name of the variable, use an explicit mapping value {[<<"my-container">>, <<"my-variable-name">>], [<<"the">>, <<"path">>, <<"to">>, <<"value">>]}. build the values for account/user/device and merge them, set the value if the merged value is not empty

2022-12-20 17:56 UTC, sanjeevie6353 commented
Closing the PR as the change on this PR is already merged onto master.

2022-12-20 17:57 UTC, closed without merging