KPUS-4: implement generic push notification mechanism
2600hz/kazoo-core pull request #555
Opened 2022-12-13 19:06 UTC by danielfinke

- apply `kapi_pusher` changes from db1a1bf in core
- add `endpoint_push_req` for sending generic push notifications
  - enables sending to an individual device or all push-enabled devices
    for a user
  - covers common push payload props between APNs/FCM
  - covers some select unique push payload props on APNs or FCM
- add API definition funs for `kazoo-ast`

## Related PRs
- https://github.com/2600hz/kazoo-pusher/pull/19

2022-12-13 21:33 UTC, harenson requested changes

2022-12-13 21:33 UTC, harenson commented on kazoo_amqp/src/api/kapi_pusher.erl
> +-export([endpoint_push_req_definition/0
The event's definition function is not exported because it can be get via `kapi_pusher:api_definition({EVENT_NAME})`.

2022-12-13 21:33 UTC, harenson commented on kazoo_amqp/src/api/kapi_pusher.erl
> +-export([publish_endpoint_push_req/1, publish_endpoint_push_req/2]).
Since a separate export directive is being used for _endpoint_push_ functions, please move this function into that directive as well.

2022-12-13 21:33 UTC, harenson commented on kazoo_amqp/src/api/kapi_pusher.erl
> -    kz_amqp_util:kapps_exchange().
Is not this exchange needed anymore by this module?

2022-12-15 20:20 UTC, danielfinke commented on kazoo_amqp/src/api/kapi_pusher.erl
> -    kz_amqp_util:kapps_exchange().
Right, it's not needed. It was unused before and is still unused

2022-12-21 20:17 UTC, harenson commented on kazoo_documents/src/kzd_devices.erl
> +-export([push/1]).
What about _set_push/2_ setter function?

2022-12-28 19:29 UTC, merged

2023-01-03 17:55 UTC, danielfinke commented on kazoo_documents/src/kzd_devices.erl
> +-export([push/1]).
@harenson addressed in https://github.com/2600hz/kazoo-core/pull/562 and https://github.com/2600hz/kazoo-pusher/pull/21 🙂