KCRO-122: Screenpop endpoint to segment screenpops per user
2600hz/kazoo-core pull request #563
Opened 2023-01-04 16:28 UTC by Navoda626

KCRO-122: Screenpop endpoint to segment screenpops per user

Adding permission object for screenpops crossbar_listing view and document accessor changes

2023-01-04 20:25 UTC, icehess requested changes

2023-01-04 20:25 UTC, icehess commented on kazoo_couch/priv/couchdb/views/account-crossbar_listings.json
> +                "      defaultValue.permissions = doc.permissions;",
See the comment https://github.com/2600hz/kazoo-crossbar/pull/408#discussion_r1061851684

2023-01-10 14:26 UTC, Navoda626 commented on kazoo_couch/priv/couchdb/views/account-crossbar_listings.json
> +                "      defaultValue.permissions = doc.permissions;",
This is unchanged because for querying user summary crossbar_view:find/4 function is used

2023-01-25 16:34 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_screenpops.erl.src
> +permissions(Doc) ->
This new functionality needs to be migrated to the .erl version of this file.

2023-01-30 13:11 UTC, Navoda626 commented on kazoo_documents/src/kzd_screenpops.erl.src
> +permissions(Doc) ->
These are merged

2023-02-08 16:16 UTC, jamesaimonetti commented on kazoo_couch/priv/couchdb/views/account-crossbar_listings.json
> +                "      defaultValue.permissions = doc.permissions;",
@icehess do you agree? is this resolved now?

2023-02-08 19:04 UTC, merged