KZOO-304: Implementation sanitizer for HTML input
2600hz/kazoo-core pull request #610
Opened 2023-03-03 16:21 UTC by dhuynh-Kazoo

2023-03-03 21:23 UTC, icehess requested changes
In first pass this looks good to me.
As you notice we are a bit strict about code formatting.
There are some handy way to run the formatter. The simplest way is to make your change, commit (not push yet) and run:

```
make fmt
```

This will format your codes, you need to commit those changes again.

We use 4 space (no tab at all)

Also we use comma-first list, tuple at etc... like this:

```
-export([apply/1
        ,parse/1
        ,traverse/1
        ,scrub_css/1
        ,to_html/1
        ]
       ).
```

2023-03-03 21:23 UTC, icehess commented on kazoo_web/src/kz_html_sanitizer.erl
> +          end,
I think this extra. you can omit it, you already convert list to binary in previous func clause.

But alos to confirm you are operating on binary, then pattern match in the header, and let code crash as soon as possible.

```suggestion
parse(<<HTML/binary>>) ->
```

2023-03-03 21:23 UTC, icehess commented on kazoo_web/src/kz_html_sanitizer.erl
> +  of
We usually drop orelse/andalso/and/or to new line like this:

```suggestion
    case lists:member(Tag, proplists:get_keys(?ALLOW_TAG_WITH_NORMAL_ATTRIBUTES))
        orelse lists:member(Tag, proplists:get_keys(?ALLOW_TAG_WITH_URI_ATTRIBUTES))
    of
```

2023-03-03 21:23 UTC, icehess commented on kazoo_web/src/kz_html_sanitizer.erl
> +         to_html/1]).
We always format list as comma-first:
```suggestion
-export([apply/1
        ,parse/1
        ,traverse/1
        ,scrub_css/1
        ,to_html/1
        ]
       ).
```

2023-03-03 21:26 UTC, icehess requested changes
@dhuynh-Kazoo Also please always make sure you have the ticket number in the PR title;
`KZOO-304: Implementation sanitizer for HTML input`

And also please always add some description to your first commit and also add description to PR.

2023-03-03 21:52 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +  of
Also use the `props` module in kazoo_stdlib instead of `proplists` when possible

2023-03-06 23:58 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +         to_html/1]).
Formatted

2023-03-06 23:59 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +  of
Replaced with props

2023-03-07 00:00 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +  of
formatted case...of

2023-03-07 00:01 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +          end,
Ongoing, I am checking the fields in the account then I'll standardize the input type

2023-03-07 16:21 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    lists:flatten([Head_2] ++ Tail_1);
`[Head_2 | Tail_1]` should be equivalent and not rely on the append operator

2023-03-07 16:23 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +scrub({<<"script">>, _, _}) -> [];
Empty list seems like an odd choice. Why not use `undefined` and filter it out in traverse/1?

2023-03-07 16:24 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +collapse_list(List) ->
In general, use pattern-matching in the function clause when possible, then in case statements.

```erlang
collapse_list([X]) -> X;
collapse_list(L) -> L.
```

2023-03-07 16:29 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +traverse([]) -> [];
Seems like a list comprehension to map a function of the HTML node would be easier to read?

```erlang
traverse(HTMLNodes) ->
    [Scrubbed || HTMLNode <- HTMLNodes, Scrubbed <- [handle_node(HTMLNode)], Scrubbed =/= 'undefined'].
```

Something along these lines, then `handle_node/1`  becomes the traverse clauses below for handling the tuples. And if scrub returns 'undefined', you can filter scrubbed results.

2023-03-07 16:30 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    case Res of
`Res =/= 'nomatch'.` unless you plan to use the matched groups

2023-03-13 13:29 UTC, dhuynh-Kazoo commented
Good morning @jamesaimonetti and @icehess , could you please review the code again? I changed the implementation to check if the HTML contains XSS or not. The sanitizer function was removed.

2023-03-13 18:26 UTC, jamesaimonetti commented on kazoo_schemas/src/kz_json_schema_extensions.erl
> +            lager:debug("Announcement contains cross-site scripting ~s", [ErrorMsg]),
log lines start with lowercase characters, as part of the full log line in syslog

2023-03-13 18:27 UTC, jamesaimonetti commented on kazoo_schemas/src/kz_json_schema_extensions.erl
> +                                            ,State)
Drop the paren to the newline

2023-03-13 18:27 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +-define(VALID_SCHEMES, ["http", "https", "mailto"]).
Unless required to, use binaries instead of strings

2023-03-13 18:29 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +-define(HTTP_LIKE_SCHEME, lists:concat(["(?<scheme>.+?)", "(", ?PROTOCOL_SEPARATOR, ")//"])).
The compiler will flatten strings, no need to run lists:concat I think.

`-define(M, "foo" "bar" "baz").` will render as `-define(M, "foobarbaz").`

2023-03-13 18:30 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +                lists:filtermap(fun([{Pos1, Len1}, {Pos2, Len2},{Pos3, Len3}]) ->
typically like to put this into a called function, to avoid large horizontal nesting.

2023-03-14 01:50 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +                lists:filtermap(fun([{Pos1, Len1}, {Pos2, Len2},{Pos3, Len3}]) ->
Done

2023-03-14 01:50 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +-define(HTTP_LIKE_SCHEME, lists:concat(["(?<scheme>.+?)", "(", ?PROTOCOL_SEPARATOR, ")//"])).
Done

2023-03-14 01:50 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_sanitizer.erl
> +-define(VALID_SCHEMES, ["http", "https", "mailto"]).
Done

2023-03-14 01:50 UTC, dhuynh-Kazoo commented on kazoo_schemas/src/kz_json_schema_extensions.erl
> +                                            ,State)
Done

2023-03-14 01:51 UTC, dhuynh-Kazoo commented on kazoo_schemas/src/kz_json_schema_extensions.erl
> +            lager:debug("Announcement contains cross-site scripting ~s", [ErrorMsg]),
Done

2023-03-15 18:04 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    Res = lists:filtermap(fun(Elem) ->
This could just be `Res = lists:filtermap(fun find_xx_in_css/1, Test),` no need for the anonymous function

2023-03-15 18:04 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +has_xss_items(<<>>) -> false;
Ticky atoms

2023-03-15 18:05 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    Res = lists:filtermap(fun(Elem) ->
same here, just pass `fun find_xss_in_css/1` instead

2023-03-15 18:06 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    lists:filtermap(fun(Attr) ->
here too

2023-03-15 18:07 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +get_xss_items_handler({comment, _}) -> [];
Can you explain why you chose `[]` as the return value here and in other clauses below?

You could try returning `'undefined'`; then instead of lists:flatten above you could `props:filter_undefined(Acc)`. Might be worth comparing run times of the two approaches.

2023-03-15 18:09 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    Text1 = re:replace(Text,
Commas drop to newline:

```erlang
re:replace(Text
           ,"..."
```

2023-03-15 18:09 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +                       [{return, list}, global]),
Matching parens should be vertically aligned, drop `),` down to align with `re:replace(` above

2023-03-15 18:10 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +                  _Property = string:substr(Text1, Pos2+1, Len2),
seems unnecessary

2023-03-15 18:11 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +        case re:run(Text1,"([-\\w]+)\\s*:\\s*([^:;]*)",[global]) of
why not capture the values of the groups instead of the positions? Then you wouldn't need to do the string:substr above right?

2023-03-15 18:14 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +%%% * CSS properties and their values, formatted likes <word-word>: <word-word>
html escape the `<` and `>` for edoc to pass

2023-03-15 18:15 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +%%% * CSS properties and their values, formatted likes <word-word>: <word-word>
escape here too

2023-03-15 18:18 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +%% If it detects any XSS item, returns `true`. Otherwise, it continue traverse the next node
edoc doesn't seem to like the backticks here, maybe just remove

2023-03-15 18:19 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +-include("kazoo_html_sanitizer_whitelist.hrl").
include goes after export

2023-03-15 21:22 UTC, icehess commented on kazoo_web/src/kz_html_xss.erl
> +%% If it detects any XSS item, returns `true`. Otherwise, it continue traverse the next node
Edoc treat some characters, to avoid that use Edoc code format.
It starts with a back tick ` and ENDS with a single quote

https://www.erlang.org/doc/apps/edoc/chapter.html#verbatim-quoting

2023-03-15 21:23 UTC, icehess commented on kazoo_web/src/kz_html_xss.erl
> +%%% * CSS properties and their values, formatted likes <word-word>: <word-word>
Edoc treat some characters, to avoid that use Edoc code format.
It starts with a back tick ` and ENDS with a single quote

https://www.erlang.org/doc/apps/edoc/chapter.html#verbatim-quoting

2023-03-20 05:01 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_xss.erl
> +get_xss_items_handler({comment, _}) -> [];
Hi @jamesaimonetti , my idea is that the function may return a prop list like `[{xss_script, Items}, {xss_attr, Items}, {xss_script, Items}]` for the type of XSS that detected in HTML. If we do not find anything, return the `[]`.

2023-03-20 06:29 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_xss.erl
> +has_xss_items(<<>>) -> false;
Hi @jamesaimonetti, I deleted this case because the below one already handles it. But what do you mean by `ticky atoms`?

2023-03-20 06:45 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_xss.erl
> +get_xss_items_handler({comment, _}) -> [];
Aslo in the `kz_html_sanitizer:scrub/1` I already changed `[]` to `undefined`

2023-03-20 06:51 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_xss.erl
> +        case re:run(Text1,"([-\\w]+)\\s*:\\s*([^:;]*)",[global]) of
Hi @jamesaimonetti , I am not sure I get you well. But the group can contain many pairs like `property: value`. For example, `color: red; text-align: center;`. So I think it is better to check the position of each pair. Let me know if I do not get you.

2023-03-20 15:14 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +has_xss_items(<<>>) -> false;
In KAZOO, we put single quotes around all atoms, rather than relying on the implicit assumption that `true` is an atom, we make it explicit with `'true'`

2023-03-20 15:17 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +get_xss_items_handler({comment, _}) -> [];
I wonder if it would make sense, at this point, to just iterate over things looking for an invalid item and return an error message with the bad value. You could even do a local `throw({error, Item})` to escape the recursion and catch it at the initial call to return.

Another option would be to fold over the items instead and add to the accumulator as you go.

The idea being to avoid iterating over the list again to flatten it.

2023-03-20 15:19 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +        case re:run(Text1,"([-\\w]+)\\s*:\\s*([^:;]*)",[global]) of
Sure, but compare:

```erlang
1> re:run(<<"color:red; text-align: center;">>,<<"([-\\w]+)\\s*:\\s*([^:;]*)">>,[global]).
{match,[[{0,9},{0,5},{6,3}],[{11,18},{11,10},{23,6}]]}

2> re:run(<<"color:red; text-align: center;">>,<<"([-\\w]+)\\s*:\\s*([^:;]*)">>,[global, {capture, all_but_first, binary}]).
{match,[[<<"color">>,<<"red">>],
        [<<"text-align">>,<<"center">>]]}
```
No need to do all the lookups to find the matches when `re` can do it for you.

2023-03-21 14:00 UTC, dhuynh-Kazoo commented on kazoo_web/src/kz_html_xss.erl
> +get_xss_items_handler({comment, _}) -> [];
Hi @jamesaimonetti, I think both ways are the same because in case we have SubNode in a Node, We need to call the origin function inside, so we have to add the found items to the accumulator and flatten to get all

2023-03-22 15:18 UTC, jamesaimonetti commented on kazoo_schemas/src/kz_json_schema_extensions.erl
> +        false -> State;
tickies

2023-03-22 15:21 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +               HTML,
commas should prefix the arg:
```erlang
re:replace(HTML
          ,<<"...regex...">>
          ,[{'return', 'binary'}, 'global']
          )
```

2023-03-22 15:22 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    [Res || Node <- Nodes, Res <- [handle_node(Node)], Res =/= 'undefined'];
generators and filters should be on their own lines:

```erlang
    [Res || Node <- Nodes,
            Res <- [handle_node(Node)],
            Res =/= 'undefined'
    ];
```

2023-03-22 15:26 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    Fun = fun({Attr, Value}) ->
In general, when a `fun()` doesn't enclose vars from the outer scope, I would prefer these to be named functions instead:

```erlang
is_style_attribute_valid({Attr, _Value}) ->
  lists:member(Attr, [...]).

scrub({<<"style">>, Attrs, Text}) ->
    Attrs1 = [Attr || Attr <- Attrs, is_style_attribute_value(Attr)],
    {<<"style">>, Attrs1, scrub_css(Text)};
```

2023-03-22 15:26 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +                      Res =/= 'undefined'],
drop end of list comprehension to new line

2023-03-22 15:27 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    case re:run(Src, ?ALLOWED_MIMETYPES_SOURCE, [global]) of
If you run `make elvis` you should get warnings about all untickied atoms that KAZOO cares about.

2023-03-22 15:28 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +                          'true' -> NewVal = scrub_css_val(Value),
I don't think the temp var is necessary here, why not `[Property, ": ", scrub_css_val(Value)]`?

Also, multi-line clauses should start on new lines under the clause

2023-03-22 15:28 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_sanitizer.erl
> +    Fun = fun([SubMatched, Property, Value], Acc) ->
This should be a named function

2023-03-22 15:30 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    'nomatch' == re:run(Src, ?ALLOWED_MIMETYPES_SOURCE, ['global']);
In general, KAZOO prefers to use `=:=` and `=/=` unless there's a specific need for `==` instead.

2023-03-22 15:30 UTC, jamesaimonetti commented on kazoo_web/src/kz_html_xss.erl
> +    Fun = fun([Matched]) ->
named fun

2023-03-22 23:42 UTC, merged