KZOO-308: added functionality to create call record from channel_create
2600hz/kazoo-core pull request #624
Opened 2023-03-21 15:06 UTC by nkarunarathne

added kapps_call ability to create the call from channel_create so that that event can be used to start recording via kapps_call_recording

2023-03-21 15:24 UTC, jamesaimonetti commented
The Call record created from CHANNEL_CREATE won't have a call control queue available, so commands using kapps_call_command (for instance) won't work. I assume this is for use in ecallmgr only?

2023-03-22 18:35 UTC, k-anderson commented
@jamesaimonetti you are correct but the presedent already exists as we have "from_route_req", ect.  There are some places where having the Call record early is valid, because util functions use call parameters to calculate something.

Simple example from cf_route_req:

```
    Call = kapps_call:exec(Routines, kapps_call:from_route_req(RouteReq)),
    case is_binary(kapps_call:account_id(Call))
```

2023-03-31 16:49 UTC, lazedo commented on kazoo_call/src/kapps_call_recording.erl
> +    Media = props:filter_undefined(
no need for `props:filter_undefined` as `kz_json:from_list/1` already does it, any reason for this change ?

2023-03-31 16:52 UTC, lazedo commented on kazoo_call/src/kapps_call_recording.erl
> +    RecordingId = kz_json:get_ne_binary_value(<<"media_id">>, Data, kz_binary:rand_hex(16)),
if the value configured doesn't change it will try create duplicate docs, why is this being changed ?

2023-03-31 16:57 UTC, lazedo requested changes
media_id and props:filter_undefined should be changed

2023-04-01 09:12 UTC, lazedo commented on kazoo_call/src/kapps_call_recording.erl
> +    RecordAsStereo = kz_json:is_true(<<"stereo">>, Data),
```suggestion
    RecordAsStereo = kz_json:get_boolean_value(<<"stereo">>, Data),
```

2023-04-01 09:12 UTC, lazedo commented on kazoo_call/src/kapps_call_recording.erl
> +    RecordAsStereo = kz_json:is_true(<<"stereo">>, Data),
the default is to record with stereo in the absence of `Channels-As-Stereo`, this is changing behavior

2023-04-02 04:44 UTC, merged