KZOO-301: Add delete_bucket/2 fun to kazoo_token_buckets
2600hz/kazoo-core pull request #663
Opened 2023-05-04 03:28 UTC by dhuynh-Kazoo

This utility function will be called in cb_modules_utils for deleting the bucket to unlock account purpose

2023-05-26 16:36 UTC, dhuynh-Kazoo commented
This utility function will be called in cb_modules_utils for deleting the bucket to unlock account purpose

Main implementation for locking many failed login attempts: - https://github.com/2600hz/kazoo-crossbar/pull/467
Test case with user_auth login - https://github.com/2600hz/kazoo-properly/pull/150

2023-06-02 17:45 UTC, icehess requested changes

2023-06-02 17:45 UTC, icehess commented on kazoo_token_buckets/src/kz_token_bucket.erl
> +delete_bucket(Srv) ->
We already have `stop/1`, you can use that maybe? also can you add `get_callid()` to `stop` too so we get visibility in log for that request id?

2023-09-08 17:57 UTC, jamesaimonetti commented on kazoo_token_buckets/src/kz_buckets.erl
> +            CallId = kz_token_bucket:get_callid(),
This isn't necessary, the proc's callid is set higher up (in Crossbar or Callflow) so logging here will reflect that

2023-09-08 20:37 UTC, merged