[master] kcro-188-ListsApiEnhancements
2600hz/kazoo-core pull request #685
Opened 2023-07-11 03:42 UTC by kdamas93

Related changes for lists API support, more detail can be found in this reference
https://github.com/2600hz/kazoo-crossbar/pull/500

2023-07-20 15:53 UTC, jamesaimonetti requested changes

2023-07-20 15:53 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_list_entries.erl
> -%%% This Source Code Form is subject to the terms of the Mozilla Public
Don't remove this

2023-07-20 15:53 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_lists.erl
> -%%% This Source Code Form is subject to the terms of the Mozilla Public
Don't remove this

2023-07-25 15:06 UTC, kdamas93 commented on kazoo_documents/src/kzd_list_entries.erl
> -%%% This Source Code Form is subject to the terms of the Mozilla Public
This change has been reverted so that it has the original document.

2023-07-25 15:07 UTC, kdamas93 commented on kazoo_documents/src/kzd_lists.erl
> -%%% This Source Code Form is subject to the terms of the Mozilla Public
This change has been reverted so that it has the original document.

2023-07-25 17:48 UTC, nkarunarathne commented on kazoo_documents/src/kzd_list_entries.erl.src
> +-spec history(doc()) -> kz_json:objects().
[] is not a json object. may need to change the return type in the spec.

maybe something like kz_json:objects() | []

2023-07-28 20:49 UTC, kdamas93 commented on kazoo_documents/src/kzd_list_entries.erl.src
> +-spec history(doc()) -> kz_json:objects().
change applied!

2023-08-11 17:33 UTC, icehess requested changes
Do you also need to update `lists` views? if the `number` field is changed the view needs to be updated (if you change `lists` also update `crossbar-listings` too).

Also if `number` field is changed you may also need to search all apps and update the code there, for example this shows callflow needs to be update:

```
$ ag lists/match core/ applications/
....
....
applications/callflow/src/module/cf_cidlistmatch.erl
58:    case kz_datamgr:get_results(AccountDb, <<"lists/match_prefix_in_list">>, [{'keys', Keys}]) of

applications/callflow/src/module/cf_lookupcidname.erl
76:    case kz_datamgr:get_results(AccountDb , <<"lists/match_prefix_in_list">>, ViewOptions) of
```

Repaeat this for all other lists views.

2023-08-15 09:47 UTC, nkarunarathne commented on kazoo_documents/src/kzd_list_entries.erl
> +-spec contacts(doc()) -> kz_json:objects().
change the spec the way you done in history function.

return type ->  `kz_json:objects() | [].`

2023-09-25 20:35 UTC, merged