crm shared module
2600hz/kazoo-core pull request #691
Opened 2023-07-20 17:43 UTC by kusalfernando

This include CRM shared module for authentication and get caller info which is used by qubicle.

2023-07-20 20:53 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +-export([authenticate/1, caller_info/1]).
Please format according to project standards. Consult other modules for guidance if needed or read the [contributing guide](https://github.com/2600hz/kazoo5/blob/master/CONTRIBUTING.md)

2023-07-20 20:55 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +authenticate_resp(Message) ->
Function names to return booleans should indicate so. `is_authentication_reply` for instance

2023-07-20 20:56 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +-module(kapi_crm).
Please consult other kapi modules, define the AMQP payload definitions, builders, validators, and publishers.

2023-07-20 20:58 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +-module(kapi_crm).
The caller10 guide has a section all about kapi modules:
https://github.com/2600hz/docs-training/blob/666341a35bc525a16cfd2425225d3c91667ea818/caller10/06_callflows.org#the-kapi-module

2023-07-27 23:14 UTC, jamesaimonetti requested changes

2023-07-27 23:14 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +        ,publish_authenticate/2]).
Drop `]).` to newline as per project standards

2023-07-27 23:14 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.hrl
> +                                      ,<<"Caller_Name__c">>
where is this `__c` suffix coming from?

2023-07-28 13:24 UTC, kusalfernando commented on kazoo_amqp/src/api/kapi_crm.hrl
> +                                      ,<<"Caller_Name__c">>
It's coming from Salesforce and we don't format it yet as we are not sure about the format of the data yet.

2023-07-28 22:32 UTC, jamesaimonetti requested changes

2023-07-28 22:32 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +    EventName = <<"authenticate-reply">>,
using underscores is consistent with other EventName settings

2023-07-28 22:32 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +    ,caller_info_resp_definition()].
Drop `]` to newline

2023-07-31 18:26 UTC, icehess requested changes

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, ?CALLER_INFO_RESPONSE_HEADERS}
I advise to not use macro here since you are not even share these headers anywhere else.

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.erl
> +    Category = <<"crm-salesforce">>,
hmm, use underscore to be consistence with other api

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, ?CALLER_INFO_RESPONSE_HEADERS}
do the same for other definition functions.

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_types/2, []}
I suggest to always type your data. look at other kapi modules, like here you have `Client-ID` (pay attention to capital `D` here too). you can type it like:
```erlang
{<<"Client-ID">>, fun kz_term:is_binary/1} %% or kz_term:is_ne_binary/1 if you want to force be non empty string
```

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_types/2, []}
also do the same for all other api definition functions.

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.hrl
> +-define(AUTH_RESPONSE_HEADERS_OPT, [<<"instance_url">>
Top level keys in all Kapi modules are CamelCase and use `-` , please do the same here and be consistence with the rest of kapi modules.

If you are just want to send the exact data you received from and external service, maybe you can just put those data inside `CRM-Response` with type `kz_json:is_object/1` in this case? What do you think?

This applies to the other headers here, apply this to all of them.

2023-07-31 18:26 UTC, icehess commented on kazoo_amqp/src/api/kapi_crm.hrl
> +                                      ,<<"Caller_Name__c">>
Look at my other comment, if you want to reply unchanged response from Salesforce then don't set those in top level, set them in `Salesforce-Response` as is `kz_json:is_object` type.

2023-07-31 20:16 UTC, kusalfernando commented on kazoo_amqp/src/api/kapi_crm.hrl
> +-define(AUTH_RESPONSE_HEADERS_OPT, [<<"instance_url">>
I agree with that and I will go with `Auth-Response` and type is `kz_json:is_object/1`.

2023-07-31 22:35 UTC, jamesaimonetti requested changes
No salesforce references

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/priv/couchdb/schemas/kapi.crm.authenticate.json
> +                "crm-salesforce"
I would have assumed event category is `crm` for all of these, and the particular CRM module (salesforce) does salesforcey stuff with the payload

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/priv/couchdb/schemas/kapi.crm.caller_info.json
> +                "crm-salesforce"
same here

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/priv/couchdb/schemas/kapi.crm.caller_info_reply.json
> +                "crm-salesforce"
here too

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +    Category = <<"crm_salesforce">>,
just `crm`

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_description/2, <<"Query caller info in Salesforce">>}
just `in a CRM` - remove salesforce references

2023-07-31 22:35 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, [<<"Caller-ID">>
I wonder how CRM info like this is stored? If in the account database, I would suggest passing account ID / doc ID instead of sensitive client id/secret/token info. Let the CRM app fetch the sensitive stuff from the DB (or wherever)

2023-07-31 22:42 UTC, kusalfernando commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, [<<"Caller-ID">>
This was planned with @mark2600 to pass the credentials into CRM when the request is made from qubicle.

2023-07-31 23:01 UTC, mark2600 commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, [<<"Caller-ID">>
it is ultimately stored in the db, so this is certainly an optimization to be done in the future.  unless you have major concerns with this i would say we should move ahead as is for now, given the impending code freeze.

2023-07-31 23:23 UTC, jamesaimonetti commented on kazoo_amqp/src/api/kapi_crm.erl
> +              ,{fun kapi_definition:set_required_headers/2, [<<"Caller-ID">>
Seems simple enough to change though. Instead of

```erlang
handle_crm(JObj, _Props) ->
    ClientId = kz_json:get_ne_binary_value(<<"Client-ID">>, JObj),
    ...
```

it becomes
```erlang
handle_crm(JObj, _Props) ->
    AccountId = kz_json:get_ne_binary_value(<<"Account-ID">>, JObj),
    CRMConfigId = kz_json:get_ne_binary_value(<<"Config-ID">>, JObj),
    {'ok', Config} = kz_datamgr:open_cache_doc(AccountId, CRMConfigId),

    ClientId = kzd_crm:client_id(Config),
    ....
```

2023-08-01 17:03 UTC, merged