KCRO-191: Fix local available numbers listing
2600hz/kazoo-core pull request #698
Opened 2023-08-08 17:46 UTC by harenson

Properly tests: https://github.com/2600hz/kazoo-properly/pull/176

When listing available local numbers via NPANXX query, the local carrier is not honoring the given NPANXX prefix, it is only honoring the first 3 digits (NPA). `knm_local`'s changes fix it.

Also:
- Add some documentation to `props:set_values/2` function.

**NOTE**: Only knm_local carrier module is failing when NPANXX prefix is given. Other carriers are working as expected.

2023-08-08 21:48 UTC, lazedo commented on kazoo_numbers/src/knm_search.erl
> +    Opts = props:set_values(Options, Defaults),
undo this, its working as expected.

2023-08-08 21:49 UTC, lazedo commented on kazoo_numbers/src/knm_search.erl
> +    %%      end).
add the comment when we get to otp26, remove it for now

2023-08-08 21:53 UTC, lazedo commented on kazoo_numbers/src/carriers/knm_local.erl
> +                    find_more(Prefix, Quantity, Offset, AccountId, length(JObjs), QID, Numbers);
why the change ?

2023-08-08 21:54 UTC, lazedo requested changes
defaults are working as expected, they override whatever the caller may have set on those params

2023-08-09 17:06 UTC, harenson commented on kazoo_numbers/src/carriers/knm_local.erl
> +                    find_more(Prefix, Quantity, Offset, AccountId, length(JObjs), QID, Numbers);
To move the _offset_. Avoids looping forever over the same non-matching numbers.

2023-08-23 19:21 UTC, merged