AXS-101: bind for node heartbeats and adjust runnings apps accordingly
2600hz/kazoo-core pull request #699
Opened 2023-08-14 23:36 UTC by jamesaimonetti

Preconditions:
 1. Appex client is configured to run
 2. `sup kapps_config appex_client is_true is_aio_cluster` returns true

Clusters using the app marketplace will, by default, run as all-in-one KAZOO servers - meaning any app running on node N will also run on node N+1.

When node heartbeats arrive from remote nodes, kappex_controller will compare their list of running kapps to the local nodes; if any apps are running remotely that are not running locally, kappex_controller will check if the app is loadable.

If loadable, the app is attempted to be started via normal kapps_controller interactions (spawned, to avoid slow-starting apps blocking kappex_controller).

If not loadable, currently, logging will take place indicating the issue but otherwise no action is taken.

2023-08-14 23:45 UTC, jamesaimonetti commented
Include https://github.com/2600hz/kazoo-crossbar/pull/514

2023-08-15 22:54 UTC, icehess requested changes

2023-08-15 22:54 UTC, icehess commented on kazoo_appex/src/kappex_controller.erl
> +    maybe_node_bindings(kapps_config:get_is_true(?CONFIG_CAT, <<"is_aio_cluster">>, 'false')).
Wouldn't it better to use `<<"cluster">>` for category? I assume this is mostly useful for anything that wants to check what type of cluster is this?

2023-08-15 22:54 UTC, icehess commented on kazoo_appex/src/kappex_controller.erl
> +    kz_nodes_notify:notify_heartbeat().
So I guess what we want a a smooth experience for everyone, like they just need to enable the appex with less complicated steps and just starting apps.
So in that experience if someone change this settings during runtime given that the default value if `false` too, they also need to restart the kazoo_appex so bind to heartbeat.

Instead I guess it's better to always bind then move this logic of should handle the heartbeat or not to after it receives the heartbeat.

2023-08-15 22:54 UTC, icehess commented on kazoo_appex/src/kappex_controller.erl
> +    case application:load(AppName) of
What checking for load? the appex apps for sure are not loaded if it is not started in this node.

2023-08-15 23:58 UTC, icehess approved these changes

2023-08-16 17:18 UTC, merged