AXS-115: Start all bindings and event listeners for kappex, check config per event
2600hz/kazoo-core pull request #709
Opened 2023-09-05 18:40 UTC by manushiperera

Previously, appex enabled and configs were checked before starting appex-client. If it was not enabled or configured, binding process was not initiated. Once configurations are updated, it it required to restart the app. 
Now, appex client is starting without checking the configs and once app fetch request is received from kapps_controller, it is checking for the configs. 
If it is enabled and configured, proceed with the request.
Otherwise ignore the request and log the error message as below. 
15:00:30.828 [error] |0000000000|kappex_controller:104(<0.162.0>) kazoo_appex is not enabled or configured properly, unable to proceed with app fetch request

2023-09-05 21:22 UTC, jamesaimonetti requested changes
Overall the right direction, just a few small tweaks.

2023-09-05 21:22 UTC, jamesaimonetti commented on kazoo_appex/src/kappex_controller.erl
> +            is_process_alive(Pid)
I don't think we need an aliveness test. Presumably kappex_controller is alive since the binding exists (created in init/1).

2023-09-05 21:22 UTC, jamesaimonetti commented on kazoo_appex/src/kappex_controller.erl
> +            andalso appex_client_config:is_configured() of
Drop `of` to newline to match `case` and `end` indentation.

2023-09-05 21:22 UTC, jamesaimonetti commented on kazoo_appex/src/kappex_controller.erl
> +            lager:error("~s is not enabled or configured properly, unable to proceed with app fetch request"
Downgrade to `warning`, I don't think its a system-level error to not have the client configured properly.

2023-09-06 12:35 UTC, manushiperera commented on kazoo_appex/src/kappex_controller.erl
> +            is_process_alive(Pid)
Done

2023-09-06 12:35 UTC, manushiperera commented on kazoo_appex/src/kappex_controller.erl
> +            andalso appex_client_config:is_configured() of
Done

2023-09-06 12:35 UTC, manushiperera commented on kazoo_appex/src/kappex_controller.erl
> +            lager:error("~s is not enabled or configured properly, unable to proceed with app fetch request"
Done

2023-09-06 14:12 UTC, nkarunarathne commented on kazoo_directory/src/kz_directory_device.erl
> +    timer:sleep(kz_term:to_integer(?MILLISECONDS_IN_SECOND * 2)),
since MILLISECONDS_IN_SECOND = 1000 we do not need the integer conversion.

2023-09-06 14:13 UTC, nkarunarathne commented on kazoo_directory/src/kz_directory_user.erl
> +    timer:sleep(kz_term:to_integer(?MILLISECONDS_IN_SECOND * 2)),
As mentioned before, 
since MILLISECONDS_IN_SECOND = 1000 we do not need the integer conversion.

2023-09-06 14:13 UTC, nkarunarathne commented on kazoo_appex/src/appex_client_sup.erl
> +init([]) ->
do we need to match [] here.
Instead of that we can use _Args or something like that. right?
@jamesaimonetti  your thoughts on this?

2023-09-06 17:30 UTC, jamesaimonetti commented on kazoo_directory/src/kz_directory_device.erl
> +    timer:sleep(kz_term:to_integer(?MILLISECONDS_IN_SECOND * 2)),
This is unrelated to Manushi's changes, not sure why it showed up here

2023-09-06 17:31 UTC, jamesaimonetti commented on kazoo_appex/src/appex_client_sup.erl
> +init([]) ->
I prefer explicit matching when possible but in this particular case its not really a concern. Either way works for me here

2023-09-06 17:33 UTC, merged