AXS-113 : Create payload to send to appex server
2600hz/kazoo-core pull request #710
Opened 2023-09-06 07:55 UTC by manushiperera

Previously, OS type, OS release and OTP info were not provided to fetch a package from appex-server. But those information are important to select the most relevant package. 
Now, appex-client is providing OS type, OS release (OS name and OS version ID) and OTP info (OTP version, c compiler version, system architecture and ERTS version) as app headers to fetch the package from appex-server.

Headers [{<<"x-appex-kz-version">>,<<".0.1">>},
                      {<<"x-appex-mui-version">>,<<"5.3.1">>},
                      {<<"x-appex-os-type">>,<<"linux">>},
                      {<<"x-appex-os-release">>,<<"centos-7">>},
                      {<<"x-appex-arch-type">>,<<"x86_64-unknown-linux-gnu">>},
                      {<<"x-appex-c-compiler">>,<<"gcc-4.8.5">>},
                      {<<"x-appex-erts-version">>,<<"11.0.3">>},
                      {<<"x-appex-otp-version">>,<<"23.0.3">>},
                      {<<"accept">>,
                       <<"application/vnd.appex+kazoo, application/vnd.appex+monster, application/vnd.appex+commland">>},
                      {<<"authorization">>,<<"APPEX this is for testing">>}]

2023-09-06 14:17 UTC, nkarunarathne commented on kazoo_apps/src/kapps_util.erl
> +            lager:warning("retrieve of os type is resulted in an exception: ~p:~p"
may not need to format down this lagar since it is not exceeding 100 character together. 
Also, by putting it on one line will increase readability here.

2023-09-06 14:17 UTC, nkarunarathne commented on kazoo_apps/src/kapps_util.erl
> +            lager:warning("retrieve of os release is resulted in an exception: ~p:~p"
may not need to format down this lagar since it is not exceeding 100 character together. 
Also, by putting it on one line will increase readability here.

2023-09-06 14:37 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +            lager:warning("retrieve of os type is resulted in an exception: ~p:~p"
Done

2023-09-06 14:37 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +            lager:warning("retrieve of os release is resulted in an exception: ~p:~p"
Done

2023-09-06 17:40 UTC, jamesaimonetti requested changes

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    try os:type() of
How would `os:type()` crash? Under what conditions?

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +        E:Reason ->
Generally speaking, for variables that are only used for logging purposes, we prefix with `_` (so `_E:_Reason` in this case)

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    try os:cmd("cat /etc/os-release") of
I wonder if `file:read_file/1` would be a better option (no need to invoke an OS process, run cat, and capture the result when we can just read the file contents)

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    try os:cmd("cat /etc/os-release") of
The other nice thing is you get a binary() back, which we prefer for string-y data

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +            OSInfoProps = [to_kv(X, "=") || X <- string:tokens(string:trim(OSInfoStr), "\n")],
binary:split can be used once the read_file change is made

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    ,kz_term:to_binary(string:trim(V, 'both', "\""))}.
ending `}` on newline to match opening `}`

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    ,kz_term:to_binary(string:trim(V, 'both', "\""))}.
See kz_binary:strip/2 for the equivalent to `string:trim`

2023-09-06 17:40 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +    Version = kz_term:to_float(props:get_value(<<"VERSION_ID">>, OSInfoProps)),
I think we want to be more delicate here and not assume VERSION_ID is an integer or float. Look at https://www.man7.org/linux/man-pages/man5/os-release.5.html for what is considered "valid" data for this field

2023-09-06 17:43 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +                                           ,A
These don't need to be on a single line each, you can combine them into one

2023-09-06 17:44 UTC, jamesaimonetti commented on kazoo_apps/src/kapps_util.erl
> +                                           ,A
`<<"gcc-", (kz_binary:join([A, B, C], $.))/binary>>` could work too

2023-09-06 20:50 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    try os:type() of
Removed the exception handling of `os:type()`

2023-09-06 20:51 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +        E:Reason ->
Done

2023-09-06 20:52 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    try os:cmd("cat /etc/os-release") of
Use `file:read_file/1` to read the file and use `kz_binary:to_proplist/3` to create the proplist

2023-09-06 20:53 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +            OSInfoProps = [to_kv(X, "=") || X <- string:tokens(string:trim(OSInfoStr), "\n")],
Done

2023-09-06 20:53 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    ,kz_term:to_binary(string:trim(V, 'both', "\""))}.
Done

2023-09-06 20:53 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    ,kz_term:to_binary(string:trim(V, 'both', "\""))}.
used `kz_binary:to_proplist/3` to create the proplist

2023-09-06 20:53 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +                                           ,A
Done

2023-09-06 20:55 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    Version = kz_term:to_float(props:get_value(<<"VERSION_ID">>, OSInfoProps)),
Removed a-z,-,_ characters of VERSION_ID and select the first numeric value as the version number.

2023-09-07 20:28 UTC, icehess requested changes

2023-09-07 20:28 UTC, icehess commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('version')).
Instead of erts version get the actual OTP version. You can get the OTP version from the release folder of the running erlang:

```erlang
  -spec otp_version(bluepak_state:t()) -> undefined | binary().
  otp_version(_) ->
      case file:read_file(
               filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"]))
      of
          {ok, Vsn} ->
              string:trim(Vsn);
          {error, Error} ->
              lager:debug("unable to detect Erlang/OTP version from its release OTP_VERSION file: ~p", [Error]),
              undefined
      end.
```

2023-09-07 20:28 UTC, icehess commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('version')).
fyi this file exists since OTP 17 I guess

2023-09-07 20:32 UTC, icehess commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('system_architecture')).
fyi this doesn't really helpful at all. Erlang doesn't report proper name for all CPU types. I would use `os:cmd(uname -m)` and trim its result instead since `uname -m` at least gives us better answer.

But for now this is good enough, since x64_64 is the only supported arch for kazoo and we all assume everyone is running on that arch already.

2023-09-07 20:38 UTC, icehess commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('version')).
ahh, nvm, we already using `kapps_util:otp_version/0` which uses that file. that is enough then, you can drop the erts_version. OTP version already gives a a broader version which also includes erts version

2023-09-07 22:40 UTC, icehess requested changes

2023-09-07 22:40 UTC, icehess commented on kazoo_appex/src/appex_client_client.erl
>                          [<<"application/vnd.appex+", Suffix/binary>>
Hmm, this is wrong, can you please change it to:
```suggestion
                        [<<"application/vnd.bluepak+", Suffix/binary>>
```

2023-09-08 00:09 UTC, icehess requested changes

2023-09-08 00:09 UTC, icehess commented on kazoo_apps/src/kapps_util.erl
> +    <<OSID/binary, "-", OSVersionID/binary>>.
Sorry to keep making comments repeatedly, just finding things as I go checking stuff around :) 

So the release ID format is going to be the same format we are using in our CircleCI jobs. Currently we have `build-centos7` which strip the `build-` part and we use `centos7`. We are working on Rocky Linux 8 and 9 stuff too which those get translated to `rockylinux8` and `rockylinux9` respectively.

So all said, we need to stick to the same format as this is the format appex-bluepak is using from CI environment as it publishes the packages.

So drop the `-`.
```suggestion
    <<OSID/binary, OSVersionID/binary>>.
```

2023-09-08 14:01 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('version')).
Done

2023-09-08 14:01 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    kz_term:to_binary(erlang:system_info('system_architecture')).
Done

2023-09-08 14:01 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
>                          [<<"application/vnd.appex+", Suffix/binary>>
[{<<"x-appex-kz-version">>,<<".0.1">>},
            {<<"x-appex-mui-version">>,<<"5.3.1">>},
            {<<"x-appex-os-type">>,<<"linux">>},
            {<<"x-appex-os-release">>,<<"centos7">>},
            {<<"x-appex-arch-type">>,<<"x86_64">>},
            {<<"x-appex-c-compiler">>,<<"gcc-4.8.5">>},
            {<<"x-appex-otp-version">>,<<"23.0.3">>},
            {<<"accept">>,
             <<"application/vnd.bluepak+kazoo, application/vnd.bluepak+monster, application/vnd.bluepak+commland">>},
            {<<"authorization">>,<<"APPEX this is for testing">>}]

2023-09-08 14:02 UTC, manushiperera commented on kazoo_apps/src/kapps_util.erl
> +    <<OSID/binary, "-", OSVersionID/binary>>.
[{<<"x-appex-kz-version">>,<<".0.1">>},
            {<<"x-appex-mui-version">>,<<"5.3.1">>},
            {<<"x-appex-os-type">>,<<"linux">>},
            {<<"x-appex-os-release">>,**<<"centos7">>**},
            {<<"x-appex-arch-type">>,<<"x86_64">>},
            {<<"x-appex-c-compiler">>,<<"gcc-4.8.5">>},
            {<<"x-appex-otp-version">>,<<"23.0.3">>},
            {<<"accept">>,
             <<"application/vnd.bluepak+kazoo, application/vnd.bluepak+monster, application/vnd.bluepak+commland">>},
            {<<"authorization">>,<<"APPEX this is for testing">>}]

2023-09-12 22:12 UTC, merged