AXS-123 : Cleanup existing app when installing new version
2600hz/kazoo-core pull request #718
Opened 2023-09-20 18:23 UTC by manushiperera

Previously, appex client did not clean up the old app folders, while loading newly fetched app. Therefore, it can pick up the old app folders, instead of newly fetched app. 
Now, appex client is deleting all of the old app folders related with the app name, before loading newly fetched app.

2023-09-20 21:40 UTC, icehess requested changes

2023-09-20 21:40 UTC, icehess commented on kazoo_appex/src/appex_bluepak.erl
> +    _ = [file:del_dir_r(filename:join(BasePath, Dir))
I think it is good to log the directories that you are going to delete, as a warning. This may help for future debugging and also helps auditing why a certain directories was deleted.

2023-09-21 14:47 UTC, manushiperera commented on kazoo_appex/src/appex_bluepak.erl
> +    _ = [file:del_dir_r(filename:join(BasePath, Dir))
Warning log is added. 
`03:14:24.983 [warning] |0000000000|appex_bluepak:119(<0.23477.2>) before loading qubicle app; qubicle-0.1, qubicle-0.2, qubicle-0.3 old directory(s) is/are deleted from /home/manushi/kazoo5/_rel/kazoo/lib path`

2023-09-21 23:48 UTC, jamesaimonetti commented on kazoo_appex/src/appex_bluepak.erl
> +    DirList = filelib:wildcard(AppDir, BasePath),
Why not pattern-match the result of `filelib:wildcard/2` directly in the case instead of an additional function call to is_not empty? Something like:

```erlang
prior_cleanup(App) ->
    AppDir = lists:concat([App, "-*"]),
    BasePath = code:lib_dir(),

    case filelib:wildcard(AppDir, BasePath) of
        [] -> 'ok';
        DirList ->
            _ = [file:del_dir_r(filename:join(BasePath, Dir))
                 || Dir <- DirList
                ],
            lager:warning("before loading ~p app; ~s old directory(s) is/are deleted from ~s path"
                         ,[App, string:join(DirList, ", "), BasePath]
                         )
    end.
```

2023-09-22 16:57 UTC, manushiperera commented on kazoo_appex/src/appex_bluepak.erl
> +    DirList = filelib:wildcard(AppDir, BasePath),
Done

2023-09-22 20:53 UTC, merged