AXS-122: Update Appex Client with new Server API URL
2600hz/kazoo-core pull request #724
Opened 2023-09-27 17:48 UTC by manushiperera

Previously, update cluster info, get cluster info and reset cluster secret APIs were not developed with Appex client. Further link cluster, unlink cluster, fetch package and license APIs were updated in Appex server side. Now, all the mentioned APIs are available with Appex client along with the requested changes.

2023-09-27 18:24 UTC, jamesaimonetti commented on kazoo_appex/doc/appex_client_maintenance.md
> +* The owner wants to reset for any ther reasons
`other`?

2023-09-27 18:25 UTC, jamesaimonetti commented on kazoo_appex/doc/appex_client_maintenance.md
> +> Caution: This process can not be undone, your purchased app will canceled.
`cannot` and  `your purchased apps will be cancelled`

2023-09-27 18:25 UTC, icehess requested changes

2023-09-27 18:25 UTC, icehess commented on kazoo_appex/src/appex_client_client.erl
> +    Enabled = kapps_config:get_ne_binary(?CONFIG_CAT, <<"enabled">>, <<"false">>),
Don't send `enabled`. I think appex-server is always sets enabled to true on link.

I think this enabled is going to be only editable from marketplace portal, not from client side. If you set disable then client cannot call the server api at all since the authentication will check if cluster is enabled or not.

tbh I don't know why we added this, there is no use case for it rn.

Anyway don't send it from client for time being.

2023-09-27 18:25 UTC, icehess commented on kazoo_appex/src/appex_client_maintenance.erl
> +        ,update_cluster/1, update_cluster/2
thanks for adding these, it could be helpful in future. 

The function names are not fully indicate what they are doing,

How about simply it to `set_cluster_name/1` and `set_cluster_meta_kazoo_version/1`?

2023-09-27 18:26 UTC, jamesaimonetti commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
This is redundant, the existing return type says first element can be atom `ok` or atom `error`.

2023-09-27 18:27 UTC, jamesaimonetti commented on kazoo_appex/src/appex_client_client.erl
> +                Error ->
Is Error supposed to be an object? Use kz_json:get_json_value(<<"error">>, Body)` if so

2023-09-27 18:27 UTC, jamesaimonetti commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
Redundant

2023-09-27 18:27 UTC, jamesaimonetti commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
Redundant

2023-09-27 19:47 UTC, manushiperera commented on kazoo_appex/doc/appex_client_maintenance.md
> +* The owner wants to reset for any ther reasons
Done

2023-09-27 19:47 UTC, manushiperera commented on kazoo_appex/doc/appex_client_maintenance.md
> +> Caution: This process can not be undone, your purchased app will canceled.
Done

2023-09-27 19:47 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +    Enabled = kapps_config:get_ne_binary(?CONFIG_CAT, <<"enabled">>, <<"false">>),
Done

2023-09-27 19:47 UTC, manushiperera commented on kazoo_appex/src/appex_client_maintenance.erl
> +        ,update_cluster/1, update_cluster/2
Done

2023-09-27 19:48 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
Done

2023-09-27 19:48 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
Done

2023-09-27 19:48 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +          {'ok', kz_json:object()} |
Done

2023-09-27 19:49 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +                Error ->
`Error`  is already retrieved from the json object. 
So do I need to change it?

2023-09-28 06:10 UTC, manushiperera commented on kazoo_appex/src/appex_client_client.erl
> +                Error ->
Since `Error` is expected to be a `Json Object`, changed `kz_json:get_value/2` with `kz_json:get_json_value/2` function

2023-09-28 18:59 UTC, merged