KCRO-195 : As a user I want to update date from the Monster UI entry for Marketplace connector settings
2600hz/kazoo-core pull request #725
Opened 2023-10-03 19:27 UTC by manushiperera

Previously there was no function to return and set is_aio_cluster (all in one cluster) configuration. Now is_aio_cluster/0 and set_is_aio_cluster/1 functions are defined to return and set this configuration respectively. Further is_aio_cluster configuration value is added to the return of  get_public_configs function.

2023-10-03 19:28 UTC, manushiperera commented
Please find the related PR below. 
#https://github.com/2600hz/kazoo-crossbar/pull/522

2023-10-03 20:55 UTC, icehess requested changes
Can you pelase check kazoo_appex and change places that we access `is_aio_cluster` to call this `appex_client_config:is_aio_cluster/0` function instead?

2023-10-04 09:32 UTC, manushiperera commented
Done

2023-10-04 17:18 UTC, icehess approved these changes

2023-10-04 17:19 UTC, merged