KZOO-413 : Support kazoo services specifically for 402 error modal to use in conjunction with the AppSelector API
2600hz/kazoo-core pull request #734
Opened 2023-10-16 23:37 UTC by kdamas93

https://2600hz-commercial.atlassian.net/browse/KZOO-413

As a developer, I would like to support kazoo services specifically for 402 error modal to use in conjunction with the AppSelector API, a function will be created in kazoo services to support the 402 error modal to be used in conjunction with the AppSelector API

extra instructions about the task :

![image](https://github.com/2600hz/kazoo-core/assets/68119098/fa7e0244-9b8c-4828-94f7-3f42d8d18e4b)

2023-10-17 18:02 UTC, icehess requested changes

2023-10-17 18:02 UTC, icehess commented on kazoo_services/src/kz_services_quantities.erl
> +            case kz_datamgr:get_results(AccountId, <<"application/crossbar_listing">>, ViewOptions) of
When I made that comment, I was not paying attention as why this calculate function is being called and do.

The `calculate_updates` is called when you are making a change to a doc via crossbar. If you see we always recommend to use `crossbar_doc` in to deal with saving your doc. crossbar_doc is call kz_services to calculate and update the quantities passing the old doc and new (proposed) doc and kz_services can get current quantity, and check old/new doc to update the quantities. This is where `calculate_updates` is being called.

So here we have the entitlement which is already what we need. This entitlement is replacing the old apps_store doc which was a single doc to hold the apps used by the account and is users. We would use this apps_store beacuse it had all info we need to calculate how much usages this account ands it users have for each app. But here entitlement is managed by one single doc PER app, which hold this user/account usage info for us. we just need to calculate its changes (changes to the its entitlement_type). You don't need to open application (idk why i even said that tbh). the application is not something that we want to quantify here.

With all of this said, we are missing current quantity part!. If you look a bit above there is a function called `fetch_account`. This function is called when we want to get the current quantity of tings inside the account db.
This function is using `services/quantify`.

That view is special, as it doesn't exists as regular JSON file anywhere. This view is being generated dynamically by `kazoo_services_maintenance:register_views/0`. You need to update `quantify` view to also handle `application_entitlement` doc type.

2023-10-17 18:31 UTC, icehess commented on kazoo_services/src/kz_services_quantities.erl
> +            case kz_datamgr:get_results(AccountId, <<"application/crossbar_listing">>, ViewOptions) of
I slightly updated the above comment to fix some terminologies.

2023-10-18 00:00 UTC, kdamas93 commented on kazoo_services/src/kz_services_quantities.erl
> +            case kz_datamgr:get_results(AccountId, <<"application/crossbar_listing">>, ViewOptions) of
@icehess changes added to the view (`services/quantify`) , I would appreciate your comments on this change.

2023-10-18 15:38 UTC, icehess requested changes

2023-10-18 15:38 UTC, icehess commented on kazoo_services/src/kazoo_services_maintenance.erl
> +       "                    emit(['user_applications', doc.app_id], -1);"
Hmm I'not sure we want to introduce a new service item for this, we can use the same `user_apps` and `account_apps`. Ask Karl on what this should be.

2023-10-18 15:38 UTC, icehess commented on kazoo_services/src/kz_services_quantities.erl
> +            case kz_datamgr:get_results(AccountId, <<"application/crossbar_listing">>, ViewOptions) of
okay you only addressed the view, what about this function here? you don't need to open any apps, just check the entitlement type, that is all.

2023-10-18 19:00 UTC, kdamas93 commented on kazoo_services/src/kz_services_quantities.erl
> +            case kz_datamgr:get_results(AccountId, <<"application/crossbar_listing">>, ViewOptions) of
@icehess change added ! ty!

2023-10-18 19:21 UTC, icehess approved these changes

2023-10-18 19:22 UTC, merged