KZOO-413 : Support kazoo services specifically for 402 error modal to use in conjunction with the AppSelector API
2600hz/kazoo-core pull request #736
Opened 2023-10-20 23:34 UTC by kdamas93

This performs the treatment for the individual charge of applications which was reported in this video:

![image](https://github.com/2600hz/kazoo-core/assets/68119098/7c6a420d-79ae-458c-a0ed-8260423811fb)

https://github.com/2600hz/kazoo-core/assets/68119098/cbdb9b07-8e2c-4de4-b1fe-6a29f8558edf

2023-10-21 00:14 UTC, icehess requested changes

2023-10-21 00:14 UTC, icehess commented on kazoo_services/src/kz_services_plans.erl
> +    AppType = <<"commland_ui">>,
Per our discussion,  this must all applications type! the applications is the future for both MUI and commland and any that comes in the future!

2023-10-21 00:14 UTC, icehess commented on kazoo_services/src/kz_services_plans.erl
> +            Applications = [kz_doc:id(Application)|| Application <- JObjs],
~use `kzd_serviceplan_item:name/2` with `kz_doc:id/1` as default value im case there is no name~

2023-10-21 00:14 UTC, icehess commented on kazoo_services/src/kz_services_plans.erl
> +            [{<<"account_commland_apps">>, Applications}
again don't use introduce a new service category! use the old one `account_apps` and `user_apps`!

2023-10-21 00:24 UTC, icehess commented on kazoo_services/src/kz_services_plans.erl
> +            Applications = [kz_doc:id(Application)|| Application <- JObjs],
aah, nvm. this the application doc , not service plan.

there are multiple options:

1. return id as you do now, then UI needs to make subsequent API call to fetch the app metadata from API which may be come very cumbersome!
2. this application doc so you have name of the app, then return its name!
3. You can work with UI team to let them know they may expect a list of strings (the old school way) or a mix list of string and/or objects  (the new way) which consist of both the app id and app name

2025-06-05 00:08 UTC, jamesaimonetti commented
reopen with suggested changes if still relevant

2025-06-05 00:08 UTC, closed without merging