PROD-330-Part-1: add QS brackets parser to kz_http_utils
2600hz/kazoo-core pull request #75
Opened 2020-09-15 21:28 UTC by icehess

Adding a function to parse/normalize the output `cowboy:parse_qs/1` and converts brackets to nested objects/arrays.

This also converts repeated keys in QS to a list or object (e.g. `a=b&a=c => [{<<"a">>,[<<"b">>,<<"c">>]}]`).

The implementation is based on https://github.com/ljharb/qs parser.

2020-09-16 00:10 UTC, lazedo commented
@icehess a lot of commented code here, spell checking. why export `merge_objects` ? maybe this part should be move to kz_json ?

2020-09-23 21:26 UTC, jamesaimonetti requested changes

2020-09-23 21:26 UTC, jamesaimonetti commented on kazoo_stdlib/src/kz_json.erl
> +-define(IS_JSON(Term), (is_tuple(Term)
You cannot rely on this definition of JSON object representation.

Its an extra function call but `kz_json:is_json_term/1` and `kz_json:is_json_object/1` are better to use.

2020-09-23 22:23 UTC, icehess commented on kazoo_stdlib/src/kz_json.erl
> +-define(IS_JSON(Term), (is_tuple(Term)
I guess this equivalent to `kz_json:is_json_object/1`:
```
is_json_object(?JSON_WRAPPER(P)) when is_list(P) -> 'true';
```
They both looking for a `P` which a tuple with single element and the element is list.


I need to this reduce clutter and use it in `IS_OBJECT` macro.

2020-09-23 22:29 UTC, icehess commented on kazoo_stdlib/src/kz_json.erl
> +-define(IS_JSON(Term), (is_tuple(Term)
Also we can't use `kz_json:is_json_term/1` here. This is exactly looking for an object. not string, atom, integer or any other values.

2020-09-24 00:19 UTC, jamesaimonetti commented on kazoo_stdlib/src/kz_json.erl
> +-define(IS_JSON(Term), (is_tuple(Term)
Right, today that's how they're defined. Tomorrow it could be `is_json_object(#{}) -> true; is_json_object(_) -> false.` or something. Don't break the abstraction!

2020-09-28 21:10 UTC, merged