[master] KCRO-200: Extension Reassignment Error Leads to Unintended Overwrite
2600hz/kazoo-core pull request #753
Opened 2023-12-06 18:09 UTC by filipevarjao

We moved the validation for presence id from crossbar to `validate/3` function at core so we can validate it for PUT/PATCH/POST. 
[test](https://github.com/2600hz/kazoo-properly/pull/191)

2023-12-06 18:35 UTC, lazedo reviewed
clarify on the vmboxes/listing_by_mailbox usage

2023-12-06 18:35 UTC, lazedo commented on kazoo_documents/src/kzd_users.erl
> +-define(LIST_MAILBOX, <<"vmboxes/listing_by_mailbox">>).
what's the purpose of this ? user may not have a vmbox but still have a presence_id assigned

2023-12-07 11:51 UTC, filipevarjao commented on kazoo_documents/src/kzd_users.erl
> +-define(LIST_MAILBOX, <<"vmboxes/listing_by_mailbox">>).
ok

2023-12-20 18:24 UTC, jamesaimonetti requested changes

2023-12-20 18:24 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_users.erl
> +maybe_validate_presence_uniqueness(AccountId, UserId, {Doc, Errors}) ->
I'd love to see a properly test that shows what the issue is. I am not aware of a requirement that presence_id is unique to a user in an account, so at a minimum I would expect this check to be opt-in on the account/cluster level?

Thoughts on that?

2023-12-21 00:19 UTC, jamesaimonetti commented on kazoo_documents/src/kzd_users.erl
> +    case kz_json:get_value([<<"value">>, <<"presence_id">>], CbUser) of
use typed accessors

2024-01-04 11:55 UTC, filipevarjao commented on kazoo_documents/src/kzd_users.erl
> +maybe_validate_presence_uniqueness(AccountId, UserId, {Doc, Errors}) ->
https://github.com/2600hz/kazoo-properly/pull/191

2024-05-07 22:12 UTC, jamesaimonetti commented
Holding merge until we figure out whether this change should be added to KAZOO as it introduces a backwards incompatible requirement that "presence_id" be unique for users.

2024-05-10 09:38 UTC, filipevarjao commented
Decided to not presence_id to be unique.

2024-05-10 09:38 UTC, closed without merging