[master] KPIV-9: Set recordingSid with media name
2600hz/kazoo-core pull request #801
Opened 2024-03-15 01:38 UTC by dhuynh-Kazoo

Currently for twiml format in the pivot application, the `RecordingSid` is not included in the query list when sending the recorded call to the Url in `action` attribute.That cause missing this field. 
So just set MediaName to `recording_sid` of call object.

2024-03-15 12:10 UTC, sanjeevie6353 commented
Reviewed...

2024-03-15 15:45 UTC, icehess requested changes

2024-03-15 15:45 UTC, icehess commented on kazoo_translator/src/converters/kzt_twiml.erl
> +                ,{fun kzt_util:set_recording_sid/2, MediaName}
`RecordingSid` is actually must be the Document ID of the record metadata we save in the database.

Lets pause here, there are multiple issue with this code, first of all it is old and we may want to do things a bit differently these days like saving the recording the recording metadata and its media to MODB instead of account db.

I believe this code must record same as `cf_record_call`, by calling `kapps_call:start_recording/2`. Lets provide the Pivot test result to managers and then decide what to do next.

2024-04-03 01:29 UTC, dhuynh-Kazoo commented
Put on hold for decision

2024-04-25 17:14 UTC, icehess commented
Closing in favor of ticket KPIV-20

2024-04-25 17:14 UTC, closed without merging