KPIV-17: Align TwiML Conference Attributes with Kazoo
2600hz/kazoo-core pull request #816
Opened 2024-04-22 08:40 UTC by dhuynh-Kazoo

2024-04-25 17:04 UTC, icehess requested changes

2024-04-25 17:04 UTC, icehess commented on kazoo_translator/src/converters/kzt_twiml_dial.erl
> +              ,{<<"Conference-ID">>, 'undefined'} %% hardcode to use ad-hoc conference
Why setting this to `undefined`?

2024-04-29 12:48 UTC, dhuynh-Kazoo commented on kazoo_translator/src/converters/kzt_twiml_dial.erl
> +              ,{<<"Conference-ID">>, 'undefined'} %% hardcode to use ad-hoc conference
Hi @icehess, I removed it. Previously in my local test, the conference does not play welcome entry so I considered it as not working. But did the test again and can confirm it worked with ConfId

2024-05-06 15:57 UTC, dhuynh-Kazoo commented
The latest commit *4 is for reviewing and will be detached soon, moved to new PR

2024-05-23 20:28 UTC, icehess commented
We had discussion about conference features and decided this entry/exit is only support per conference and we expect it is already configured as a profile in the account. This doc should mention this so people know what to do before using this.

2024-05-23 20:28 UTC, closed without merging