KPIV-20: adding silence variables to record_call
2600hz/kazoo-core pull request #848
Opened 2024-05-30 20:14 UTC by icehess

Adds support for stop recording on silence detection for freeswitch `record_session` app. Silence detection should be set explicitly to get enabled.

2024-05-30 20:15 UTC, icehess commented
Related PRs:
- 5.4:
    - https://github.com/2600hz/kazoo-ecallmgr/pull/252
    - https://github.com/2600hz/kazoo-core/pull/869
- master
    - https://github.com/2600hz/kazoo-ecallmgr/pull/247
    - https://github.com/2600hz/kazoo-core/pull/848

2024-05-31 17:16 UTC, lazedo reviewed
would prefer a `Record-Silence-Detection` object with its related variables there

2024-06-03 08:58 UTC, lazedo requested changes
`defaults` and `checks` should be done here

2024-06-12 13:21 UTC, lazedo approved these changes

2024-06-12 13:21 UTC, merged