Modify kapi_conference module to use kapi_definition module
2600hz/kazoo-core pull request #9
Opened 2020-05-19 17:45 UTC by harenson

Depends on https://github.com/2600hz/kazoo-ecallmgr/pull/5 PR to be merged first and then rebase master and push changes here so it can pass all CI checks.

2020-05-20 19:56 UTC, lazedo requested changes

2020-05-20 19:56 UTC, lazedo commented on kazoo_amqp/src/api/kapi_conference.erl
> +publish_conference_error(Queue, Req, ContentType) ->
why the rename ?

2020-05-20 22:19 UTC, harenson commented on kazoo_amqp/src/api/kapi_conference.erl
> +publish_conference_error(Queue, Req, ContentType) ->
To match the convention with the other functions, so the event name is `conference_error` so the publish function "should" be named `publish_conference_error` that way you know it is for the `conference_error` event.

2020-05-20 22:31 UTC, lazedo commented on kazoo_amqp/src/api/kapi_conference.erl
> +publish_conference_error(Queue, Req, ContentType) ->
i don't see that as a good reason for potentially break other people's code. iirc, `conference_error` was named because it couldn't/shouldn't be `error`. it really feels strange having `kapi_conference:publish_conference_error`  because `conference` is already in the `kapi` name

2020-05-21 14:38 UTC, lazedo approved these changes

2020-05-21 14:39 UTC, merged