KECA-41: add stream command to control streaming call media to websocket
2600hz/kazoo-core pull request #980
Opened 2024-10-11 14:22 UTC by icehess

Adding dialplan command for start/stop/pause/resume kz_audio_fork and streaming call's media to a WebSocket.

The stream will the media as raw audio with PCMU (mu-law) encoding. Sample rate and number of channels are configurable.

The stream can be stopped, pause or resume. By default if no Stream-ID is given, these commands will act on all attached audio forks.

2024-10-11 14:33 UTC, icehess commented
PRs:
   - master:
       - https://github.com/2600hz/kazoo-core/pull/980
       - https://github.com/2600hz/kazoo-core/pull/1023
       - https://github.com/2600hz/kazoo-ecallmgr/pull/265
       - https://github.com/2600hz/kazoo-ecallmgr/pull/269
   - 5.4:
       - https://github.com/2600hz/kazoo-core/pull/1036
       - https://github.com/2600hz/kazoo-ecallmgr/pull/270

2024-11-13 09:50 UTC, lazedo commented on kazoo_call/src/kapps_call_command.erl
> +stream(Action, Options, Call) ->
change to `stream_command` to follow other commands

2024-11-13 09:57 UTC, lazedo requested changes
add `block` for start_stream like other commands. `b_start_stream` that sends and waits for return

I would also like to see stream_`action` instead of `action`_stream, `stream_start` instead of `stop_stream`

2024-11-13 17:57 UTC, lazedo commented on kazoo_call/src/kapps_call_command.erl
> +              ,{<<"Insert-At">>, <<"now">>}
commands that expect a return should not set `{<<"Insert-At">>, <<"now">>}`

2024-11-15 08:44 UTC, lazedo approved these changes

2024-11-15 09:07 UTC, merged